/*
 * Copyright 2011 Google Inc.
 *
 * Swiffy runtime version 3.6.1
 *
 * In addition to the Google Terms of Service (http://www.google.com/accounts/TOS),
 * Google grants you and the Google Swiffy end users a personal, worldwide,
 * royalty-free, non-assignable and non-exclusive license to use the Google Swiffy
 * runtime to host it for Google Swiffy end users and to use it in connection with
 * the Google Swiffy service.
 */
var g=void 0,h=true,j=null,k=false,aa=window,l=Object,m=document,n=Math,ba=Array,q=Number,da=Error,ea=Boolean,fa=parseInt,r=String,ga=decodeURIComponent;function ha(a,b){return a.data=b}function ia(a,b){return a.currentTarget=b}function ja(a,b){return a.keyCode=b}function ka(a,b){return a.type=b}function la(a,b){return a.toString=b}function ma(a,b){return a.length=b}function na(a,b){return a.target=b}function oa(a,b){return a.call=b}function pa(a,b){return a.start=b}
function qa(a,b){return a.returnValue=b}function ra(a,b){return a.apply=b}
var s="appendChild",t="push",sa="ymin",ta="indent",ua="getParent",va="getOwnPropertyNames",wa="shift",xa="ymax",ya="POSITIVE_INFINITY",za="width",Aa="bitmap",Ba="text",Ca="expand",Da="slice",u="replace",Ea="matrix",Fa="setCapture",v="data",Ga="floor",Ha="concat",Ia="createTextNode",Ja="getNamedItem",Ka="preventDefault",La="setAttributeNS",w="indexOf",Ma="defineProperties",Na="color",Oa="capture",Pa="ratio",Qa="setTransform",Ra="knockout",Ta="getName",Ua="charCode",Va="createElement",Wa="defineProperty",
x="keyCode",Xa="sqrt",Ya="states",y="setAttribute",Za="play",$a="handleEvent",z="path",B="depth",C="type",ab="method",bb="childNodes",cb="name",db="releaseCapture",fb="fill",gb="stop",D="toString",hb="gradient",E="length",ib="propertyIsEnumerable",jb="create",F="prototype",kb="result",lb="inner",mb="actions",nb="variable",G="createElementNS",ob="ctrlKey",H="split",pb="constructor",qb="stopPropagation",rb="glyphs",sb="hasOwnProperty",J="style",tb="body",ub="removeChild",vb="getOwnPropertyDescriptor",
wb="target",xb="lastChild",K="call",yb="frameSize",zb="start",Ab="getAttribute",Bb="init",Cb="returnValue",Db="charCodeAt",Eb="colortransform",Fb="xmin",Gb="__proto__",Hb="trackAsMenu",L="apply",Ib="filters",Jb="xmax",Kb="navigator",Lb="parentNode",Mb="update",M="height",Nb="splice",Ob="join",Pb="isCaptured",Qb="transform",Rb="nodeValue",Sb="quality",Ub="toLowerCase",N,Vb=this,Wb=function(a){var b=typeof a;if(b=="object")if(a){if(a instanceof ba)return"array";else if(a instanceof l)return b;var c=
l[F][D][K](a);if(c=="[object Window]")return"object";if(c=="[object Array]"||typeof a[E]=="number"&&typeof a[Nb]!="undefined"&&typeof a[ib]!="undefined"&&!a[ib]("splice"))return"array";if(c=="[object Function]"||typeof a[K]!="undefined"&&typeof a[ib]!="undefined"&&!a[ib]("call"))return"function"}else return"null";else if(b=="function"&&typeof a[K]=="undefined")return"object";return b},O=function(a){return a!==g},Xb=function(a){return Wb(a)=="array"},Yb=function(a){var b=Wb(a);return b=="array"||b==
"object"&&typeof a[E]=="number"},P=function(a){return typeof a=="string"},Q=function(a){return Wb(a)=="function"},Zb=function(a){a=Wb(a);return a=="object"||a=="array"||a=="function"},bc=function(a){return a[$b]||(a[$b]=++ac)},$b="closure_uid_"+n[Ga](n.random()*2147483648)[D](36),ac=0,cc=function(a,b,c){return a[K][L](a.bind,arguments)},dc=function(a,b,c){if(!a)throw da();if(arguments[E]>2){var d=ba[F][Da][K](arguments,2);return function(){var c=ba[F][Da][K](arguments);ba[F].unshift[L](c,d);return a[L](b,
c)}}else return function(){return a[L](b,arguments)}},R=function(a,b,c){R=Function[F].bind&&Function[F].bind[D]()[w]("native code")!=-1?cc:dc;return R[L](j,arguments)},ec=function(a,b){var c=ba[F][Da][K](arguments,1);return function(){var b=ba[F][Da][K](arguments);b.unshift[L](b,c);return a[L](this,b)}},T=function(a,b){function c(){}c.prototype=b[F];a.o=b[F];a.prototype=new c;a[F].constructor=a};var fc=function(a){this.stack=da().stack||"";if(a)this.message=r(a)};T(fc,da);fc[F].name="CustomError";var gc=function(a,b){for(var c=1;c<arguments[E];c++)var d=r(arguments[c])[u](/\$/g,"$$$$"),a=a[u](/\%s/,d);return a},hc=/^[a-zA-Z0-9\-_.!~*'()]*$/,ic=function(a){a=r(a);return!hc.test(a)?encodeURIComponent(a):a},oc=function(a,b){if(b)return a[u](jc,"&amp;")[u](kc,"&lt;")[u](lc,"&gt;")[u](mc,"&quot;");else{if(!nc.test(a))return a;a[w]("&")!=-1&&(a=a[u](jc,"&amp;"));a[w]("<")!=-1&&(a=a[u](kc,"&lt;"));a[w](">")!=-1&&(a=a[u](lc,"&gt;"));a[w]('"')!=-1&&(a=a[u](mc,"&quot;"));return a}},jc=/&/g,kc=/</g,
lc=/>/g,mc=/\"/g,nc=/[&<>\"]/,pc=function(a,b){if(a<b)return-1;else if(a>b)return 1;return 0};var qc=function(a,b){b.unshift(a);fc[K](this,gc[L](j,b));b[wa]();this.ih=a};T(qc,fc);qc[F].name="AssertionError";var U=function(a,b,c){if(!a){var d=ba[F][Da][K](arguments,2),e="Assertion failed";if(b){e+=": "+b;var f=d}throw new qc(""+e,f||[]);}return a};var rc=ba[F],sc=rc[w]?function(a,b,c){U(a[E]!=j);return rc[w][K](a,b,c)}:function(a,b,c){c=c==j?0:c<0?n.max(0,a[E]+c):c;if(P(a))return!P(b)||b[E]!=1?-1:a[w](b,c);for(;c<a[E];c++)if(c in a&&a[c]===b)return c;return-1},tc=rc.forEach?function(a,b,c){U(a[E]!=j);rc.forEach[K](a,b,c)}:function(a,b,c){for(var d=a[E],e=P(a)?a[H](""):a,f=0;f<d;f++)f in e&&b[K](c,e[f],f,a)},uc=function(a,b){var c=sc(a,b),d;if(d=c>=0)U(a[E]!=j),rc[Nb][K](a,c,1);return d},vc=function(a){return rc[Ha][L](rc,arguments)},wc=function(a){if(Xb(a))return vc(a);
else{for(var b=[],c=0,d=a[E];c<d;c++)b[c]=a[c];return b}},xc=function(a,b){for(var c=1;c<arguments[E];c++){var d=arguments[c],e;if(Xb(d)||(e=Yb(d))&&d[sb]("callee"))a[t][L](a,d);else if(e)for(var f=a[E],i=d[E],o=0;o<i;o++)a[f+o]=d[o];else a[t](d)}},zc=function(a,b,c,d){U(a[E]!=j);return rc[Nb][L](a,yc(arguments,1))},yc=function(a,b,c){U(a[E]!=j);return arguments[E]<=2?rc[Da][K](a,b):rc[Da][K](a,b,c)},Ac=function(a,b,c,d,e){for(var f=0,i=a[E],o;f<i;){var p=f+i>>1,A;A=c?b[K](e,a[p],p,a):b(d,a[p]);A>
0?f=p+1:(i=p,o=!A)}return o?f:~f},Bc=function(a,b){return a>b?1:a<b?-1:0},Cc=function(a,b,c){c=Ac(a,c||Bc,k,b);return c<0?(zc(a,-(c+1),0,b),h):k};var Dc=function(a,b,c){for(var d in a)b[K](c,a[d],d,a)},Ec="constructor,hasOwnProperty,isPrototypeOf,propertyIsEnumerable,toLocaleString,toString,valueOf".split(","),Fc=function(a,b){for(var c,d,e=1;e<arguments[E];e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Ec[E];f++)c=Ec[f],l[F][sb][K](d,c)&&(a[c]=d[c])}};var Gc,Hc,Ic,Jc,Kc=function(){return Vb[Kb]?Vb[Kb].userAgent:j};Jc=Ic=Hc=Gc=k;var Lc;if(Lc=Kc()){var Mc=Vb[Kb];Gc=Lc[w]("Opera")==0;Hc=!Gc&&Lc[w]("MSIE")!=-1;Ic=!Gc&&Lc[w]("WebKit")!=-1;Jc=!Gc&&!Ic&&Mc.product=="Gecko"}var Nc=Gc,Oc=Hc,Pc=Jc,Qc=Ic,Rc=Vb[Kb],Sc=(Rc&&Rc.platform||"")[w]("Mac")!=-1,Tc;
a:{var Uc="",Vc;if(Nc&&Vb.opera)var Wc=Vb.opera.version,Uc=typeof Wc=="function"?Wc():Wc;else if(Pc?Vc=/rv\:([^\);]+)(\)|;)/:Oc?Vc=/MSIE\s+([^\);]+)(\)|;)/:Qc&&(Vc=/WebKit\/(\S+)/),Vc)var Xc=Vc.exec(Kc()),Uc=Xc?Xc[1]:"";if(Oc){var Yc,Zc=Vb.document;Yc=Zc?Zc.documentMode:g;if(Yc>parseFloat(Uc)){Tc=r(Yc);break a}}Tc=Uc}
var $c=Tc,ad={},bd=function(a){var b;if(!(b=ad[a])){b=0;for(var c=r($c)[u](/^[\s\xa0]+|[\s\xa0]+$/g,"")[H]("."),d=r(a)[u](/^[\s\xa0]+|[\s\xa0]+$/g,"")[H]("."),e=n.max(c[E],d[E]),f=0;b==0&&f<e;f++){var i=c[f]||"",o=d[f]||"",p=RegExp("(\\d*)(\\D*)","g"),A=RegExp("(\\d*)(\\D*)","g");do{var ca=p.exec(i)||["","",""],V=A.exec(o)||["","",""];if(ca[0][E]==0&&V[0][E]==0)break;b=pc(ca[1][E]==0?0:fa(ca[1],10),V[1][E]==0?0:fa(V[1],10))||pc(ca[2][E]==0,V[2][E]==0)||pc(ca[2],V[2])}while(b==0)}b=ad[a]=b>=0}return b},
cd={},dd=function(a){return cd[a]||(cd[a]=Oc&&m.documentMode&&m.documentMode>=a)};var ed=!Oc||dd(9);!Pc&&!Oc||Oc&&dd(9)||Pc&&bd("1.9.1");Oc&&bd("9");var fd=function(a,b){var c;c=(c=a.className)&&typeof c[H]=="function"?c[H](/\s+/):[];var d=yc(arguments,1),e;e=c;for(var f=0,i=0;i<d[E];i++)sc(e,d[i])>=0||(e[t](d[i]),f++);e=f==d[E];a.className=c[Ob](" ");return e};var hd=function(a,b){Dc(b,function(b,d){d=="style"?a[J].cssText=b:d=="class"?a.className=b:d=="for"?a.htmlFor=b:d in gd?a[y](gd[d],b):d.lastIndexOf("aria-",0)==0?a[y](d,b):a[d]=b})},gd={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",rowspan:"rowSpan",valign:"vAlign",height:"height",width:"width",usemap:"useMap",frameborder:"frameBorder",maxlength:"maxLength",type:"type"},jd=function(a,b,c){var d=arguments,e=d[0],f=d[1];if(!ed&&f&&(f[cb]||f[C])){e=["<",e];f[cb]&&e[t](' name="',
oc(f[cb]),'"');if(f[C]){e[t](' type="',oc(f[C]),'"');var i={};Fc(i,f);f=i;delete f[C]}e[t](">");e=e[Ob]("")}e=m[Va](e);if(f)P(f)?e.className=f:Xb(f)?fd[L](j,[e][Ha](f)):hd(e,f);d[E]>2&&id(m,e,d,2);return e},id=function(a,b,c,d){function e(c){c&&b[s](P(c)?a[Ia](c):c)}for(;d<c[E];d++){var f=c[d];Yb(f)&&!(Zb(f)&&f.nodeType>0)?tc(kd(f)?wc(f):f,e):e(f)}},ld=function(a){for(var b;b=a.firstChild;)a[ub](b)},md=function(a){return a&&a[Lb]?a[Lb][ub](a):j},nd=function(a,b){var c=b[Lb];c&&c.replaceChild(a,b)},
kd=function(a){if(a&&typeof a[E]=="number")if(Zb(a))return typeof a.item=="function"||typeof a.item=="string";else if(Q(a))return typeof a.item=="function";return k};var od=function(a){od[" "](a);return a};od[" "]=function(){};!Oc||dd(9);var pd=!Oc||dd(9),qd=Oc&&!bd("8");var rd=function(){};rd[F].We=k;rd[F].hc=function(){if(!this.We)this.We=h,this.Za()};rd[F].Za=function(){this.Cg&&sd[L](j,this.Cg)};var sd=function(a){for(var b=0,c=arguments[E];b<c;++b){var d=arguments[b];Yb(d)?sd[L](j,d):d&&typeof d.hc=="function"&&d.hc()}};var td=function(a,b){ka(this,a);na(this,b);ia(this,this[wb])};T(td,rd);N=td[F];N.Za=function(){delete this[C];delete this[wb];delete this.currentTarget};N.tb=k;N.nc=h;N.stopPropagation=function(){this.tb=h};N.preventDefault=function(){this.nc=k};var ud=function(a,b){a&&this[Bb](a,b)};T(ud,td);N=ud[F];na(N,j);N.relatedTarget=j;N.offsetX=0;N.offsetY=0;N.clientX=0;N.clientY=0;N.screenX=0;N.screenY=0;N.button=0;ja(N,0);N.charCode=0;N.ctrlKey=k;N.altKey=k;N.shiftKey=k;N.metaKey=k;N.hg=k;N.ya=j;
N.init=function(a,b){var c=ka(this,a[C]);td[K](this,c);na(this,a[wb]||a.srcElement);ia(this,b);var d=a.relatedTarget;if(d){if(Pc){var e;a:{try{od(d.nodeName);e=h;break a}catch(f){}e=k}e||(d=j)}}else if(c=="mouseover")d=a.fromElement;else if(c=="mouseout")d=a.toElement;this.relatedTarget=d;this.offsetX=a.offsetX!==g?a.offsetX:a.layerX;this.offsetY=a.offsetY!==g?a.offsetY:a.layerY;this.clientX=a.clientX!==g?a.clientX:a.pageX;this.clientY=a.clientY!==g?a.clientY:a.pageY;this.screenX=a.screenX||0;this.screenY=
a.screenY||0;this.button=a.button;ja(this,a[x]||0);this.charCode=a[Ua]||(c=="keypress"?a[x]:0);this.ctrlKey=a[ob];this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.hg=Sc?a.metaKey:a[ob];this.state=a.state;this.ya=a;delete this.nc;delete this.tb};N.stopPropagation=function(){ud.o[qb][K](this);this.ya[qb]?this.ya[qb]():this.ya.cancelBubble=h};
N.preventDefault=function(){ud.o[Ka][K](this);var a=this.ya;if(a[Ka])a[Ka]();else if(qa(a,k),qd)try{(a[ob]||a[x]>=112&&a[x]<=123)&&ja(a,-1)}catch(b){}};N.Za=function(){ud.o.Za[K](this);this.ya=j;na(this,j);ia(this,j);this.relatedTarget=j};var vd=function(){},wd=0;N=vd[F];N.key=0;N.Ib=k;N.Qe=k;N.init=function(a,b,c,d,e,f){if(Q(a))this.Oe=h;else if(a&&a[$a]&&Q(a[$a]))this.Oe=k;else throw da("Invalid listener argument");this.mc=a;this.De=b;this.src=c;ka(this,d);this.capture=!!e;this.Ed=f;this.Qe=k;this.key=++wd;this.Ib=k};N.handleEvent=function(a){return this.Oe?this.mc[K](this.Ed||this.src,a):this.mc[$a][K](this.mc,a)};var xd={},yd={},zd={},Ad={},W=function(a,b,c,d,e){if(b)if(Xb(b)){for(var f=0;f<b[E];f++)W(a,b[f],c,d,e);return j}else{var d=!!d,i=yd;b in i||(i[b]={w:0,na:0});i=i[b];d in i||(i[d]={w:0,na:0},i.w++);var i=i[d],o=bc(a),p;i.na++;if(i[o]){p=i[o];for(f=0;f<p[E];f++)if(i=p[f],i.mc==c&&i.Ed==e){if(i.Ib)break;return p[f].key}}else p=i[o]=[],i.w++;f=Bd();f.src=a;i=new vd;i[Bb](c,f,a,b,d,e);c=i.key;f.key=c;p[t](i);xd[c]=i;zd[o]||(zd[o]=[]);zd[o][t](i);a.addEventListener?(a==Vb||!a.Ee)&&a.addEventListener(b,
f,d):a.attachEvent(b in Ad?Ad[b]:Ad[b]="on"+b,f);return c}else throw da("Invalid event type");},Bd=function(){var a=Cd,b=pd?function(c){return a[K](b.src,b.key,c)}:function(c){c=a[K](b.src,b.key,c);if(!c)return c};return b},Dd=function(a,b,c,d,e){if(Xb(b)){for(var f=0;f<b[E];f++)Dd(a,b[f],c,d,e);return j}d=!!d;a:{f=yd;if(b in f&&(f=f[b],d in f&&(f=f[d],a=bc(a),f[a]))){a=f[a];break a}a=j}if(!a)return k;for(f=0;f<a[E];f++)if(a[f].mc==c&&a[f][Oa]==d&&a[f].Ed==e)return Ed(a[f].key);return k},Ed=function(a){if(!xd[a])return k;
var b=xd[a];if(b.Ib)return k;var c=b.src,d=b[C],e=b.De,f=b[Oa];c.removeEventListener?(c==Vb||!c.Ee)&&c.removeEventListener(d,e,f):c.detachEvent&&c.detachEvent(d in Ad?Ad[d]:Ad[d]="on"+d,e);c=bc(c);e=yd[d][f][c];if(zd[c]){var i=zd[c];uc(i,b);i[E]==0&&delete zd[c]}b.Ib=h;e.Ke=h;Fd(d,f,c,e);delete xd[a];return h},Fd=function(a,b,c,d){if(!d.$c&&d.Ke){for(var e=0,f=0;e<d[E];e++)d[e].Ib?d[e].De.src=j:(e!=f&&(d[f]=d[e]),f++);ma(d,f);d.Ke=k;f==0&&(delete yd[a][b][c],yd[a][b].w--,yd[a][b].w==0&&(delete yd[a][b],
yd[a].w--),yd[a].w==0&&delete yd[a])}},Gd=function(a,b,c){var d=0,e=b==j,f=c==j,c=!!c;if(a==j)Dc(zd,function(a){for(var i=a[E]-1;i>=0;i--){var o=a[i];if((e||b==o[C])&&(f||c==o[Oa]))Ed(o.key),d++}});else if(a=bc(a),zd[a])for(var a=zd[a],i=a[E]-1;i>=0;i--){var o=a[i];if((e||b==o[C])&&(f||c==o[Oa]))Ed(o.key),d++}return d},Id=function(a,b,c,d,e){var f=1,b=bc(b);if(a[b]){a.na--;a=a[b];a.$c?a.$c++:a.$c=1;try{for(var i=a[E],o=0;o<i;o++){var p=a[o];p&&!p.Ib&&(f&=Hd(p,e)!==k)}}finally{a.$c--,Fd(c,d,b,a)}}return ea(f)},
Hd=function(a,b){var c=a[$a](b);a.Qe&&Ed(a.key);return c},Cd=function(a,b){if(!xd[a])return h;var c=xd[a],d=c[C],e=yd;if(!(d in e))return h;var e=e[d],f,i;if(!pd){var o;if(!(o=b))a:{o="window.event"[H](".");for(var p=Vb;f=o[wa]();)if(p[f]!=j)p=p[f];else{o=j;break a}o=p}f=o;o=h in e;p=k in e;if(o){if(f[x]<0||f[Cb]!=g)return h;a:{var A=k;if(f[x]==0)try{ja(f,-1);break a}catch(ca){A=h}(A||f[Cb]==g)&&qa(f,h)}}A=new ud;A[Bb](f,this);f=h;try{if(o){for(var V=[],eb=A.currentTarget;eb;eb=eb[Lb])V[t](eb);i=
e[h];i.na=i.w;for(var I=V[E]-1;!A.tb&&I>=0&&i.na;I--)ia(A,V[I]),f&=Id(i,V[I],d,h,A);if(p){i=e[k];i.na=i.w;for(I=0;!A.tb&&I<V[E]&&i.na;I++)ia(A,V[I]),f&=Id(i,V[I],d,k,A)}}else f=Hd(c,A)}finally{V&&ma(V,0),A.hc()}return f}d=new ud(b,this);try{f=Hd(c,d)}finally{d.hc()}return f};var Jd=function(){};T(Jd,rd);N=Jd[F];N.Ee=h;N.Bd=j;N.addEventListener=function(a,b,c,d){W(this,a,b,c,d)};N.removeEventListener=function(a,b,c,d){Dd(this,a,b,c,d)};
N.dispatchEvent=function(a){var b=a[C]||a,c=yd;if(b in c){if(P(a))a=new td(a,this);else if(a instanceof td)na(a,a[wb]||this);else{var d=a,a=new td(b,this);Fc(a,d)}var d=1,e,c=c[b],b=h in c,f;if(b){e=[];for(f=this;f;f=f.Bd)e[t](f);f=c[h];f.na=f.w;for(var i=e[E]-1;!a.tb&&i>=0&&f.na;i--)ia(a,e[i]),d&=Id(f,e[i],a[C],h,a)&&a.nc!=k}if(k in c)if(f=c[k],f.na=f.w,b)for(i=0;!a.tb&&i<e[E]&&f.na;i++)ia(a,e[i]),d&=Id(f,e[i],a[C],k,a)&&a.nc!=k;else for(e=this;!a.tb&&e&&f.na;e=e.Bd)ia(a,e),d&=Id(f,e,a[C],k,a)&&
a.nc!=k;a=ea(d)}else a=h;return a};N.Za=function(){Jd.o.Za[K](this);Gd(this);this.Bd=j};var Ld=function(a,b,c,d,e){if(!Oc&&(!Qc||!bd("525")))return h;if(Sc&&e)return Kd(a);if(e&&!d)return k;if(!c&&(b==17||b==18))return k;if(Oc&&d&&b==a)return k;switch(a){case 13:return!(Oc&&dd(9));case 27:return!Qc}return Kd(a)},Kd=function(a){if(a>=48&&a<=57)return h;if(a>=96&&a<=106)return h;if(a>=65&&a<=90)return h;if(Qc&&a==0)return h;switch(a){case 32:case 63:case 107:case 109:case 110:case 111:case 186:case 59:case 189:case 187:case 188:case 190:case 191:case 192:case 222:case 219:case 220:case 221:return h;
default:return k}};var Md=function(a,b){a&&this.Bg(a,b)};T(Md,Jd);N=Md[F];N.sc=j;N.bd=j;N.Ld=j;N.cd=j;N.cb=-1;N.$a=-1;
var Nd={3:13,12:144,63232:38,63233:40,63234:37,63235:39,63236:112,63237:113,63238:114,63239:115,63240:116,63241:117,63242:118,63243:119,63244:120,63245:121,63246:122,63247:123,63248:44,63272:46,63273:36,63275:35,63276:33,63277:34,63289:144,63302:45},Od={Up:38,Down:40,Left:37,Right:39,Enter:13,F1:112,F2:113,F3:114,F4:115,F5:116,F6:117,F7:118,F8:119,F9:120,F10:121,F11:122,F12:123,"U+007F":46,Home:36,End:35,PageUp:33,PageDown:34,Insert:45},Pd={61:187,59:186},Qd=Oc||Qc&&bd("525");N=Md[F];
N.kg=function(a){if(Qc&&(this.cb==17&&!a[ob]||this.cb==18&&!a.altKey))this.$a=this.cb=-1;Qd&&!Ld(a[x],this.cb,a.shiftKey,a[ob],a.altKey)?this[$a](a):this.$a=Pc&&a[x]in Pd?Pd[a[x]]:a[x]};N.lg=function(){this.$a=this.cb=-1};
N.handleEvent=function(a){var b=a.ya,c,d;Oc&&a[C]=="keypress"?(c=this.$a,d=c!=13&&c!=27?b[x]:0):Qc&&a[C]=="keypress"?(c=this.$a,d=b[Ua]>=0&&b[Ua]<63232&&Kd(c)?b[Ua]:0):Nc?(c=this.$a,d=Kd(c)?b[x]:0):(c=b[x]||this.$a,d=b[Ua]||0,Sc&&d==63&&!c&&(c=191));var e=c,f=b.keyIdentifier;c?c>=63232&&c in Nd?e=Nd[c]:c==25&&a.shiftKey&&(e=9):f&&f in Od&&(e=Od[f]);a=e==this.cb;this.cb=e;b=new Rd(e,d,a,b);try{this.dispatchEvent(b)}finally{b.hc()}};
N.Bg=function(a,b){this.cd&&this.detach();this.sc=a;this.bd=W(this.sc,"keypress",this,b);this.Ld=W(this.sc,"keydown",this.kg,b,this);this.cd=W(this.sc,"keyup",this.lg,b,this)};N.detach=function(){if(this.bd)Ed(this.bd),Ed(this.Ld),Ed(this.cd),this.cd=this.Ld=this.bd=j;this.sc=j;this.$a=this.cb=-1};N.Za=function(){Md.o.Za[K](this);this.detach()};var Rd=function(a,b,c,d){d&&this[Bb](d,g);ka(this,"key");ja(this,a);this.charCode=b;this.repeat=c};T(Rd,ud);var Sd=function(){};(function(a){a.oa=function(){return a.vg||(a.vg=new a)}})(Sd);Sd[F].Dg=0;Sd[F].Da=function(){return":"+(this.Dg++)[D](36)};Sd.oa();var Td="StopIteration"in Vb?Vb.StopIteration:da("StopIteration"),Ud=function(){};Ud[F].next=function(){throw Td;};Ud[F].Ag=function(){return this};var Vd=function(a,b){this.Ya={};this.X=[];var c=arguments[E];if(c>1){if(c%2)throw da("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else a&&this.jg(a)};N=Vd[F];N.w=0;N.Jd=0;N.ad=function(){this.Pd();for(var a=[],b=0;b<this.X[E];b++)a[t](this.Ya[this.X[b]]);return a};N.pc=function(){this.Pd();return this.X[Ha]()};N.Jb=function(a){return l[F][sb][K](this.Ya,a)};
N.Pd=function(){if(this.w!=this.X[E]){for(var a=0,b=0;a<this.X[E];){var c=this.X[a];l[F][sb][K](this.Ya,c)&&(this.X[b++]=c);a++}ma(this.X,b)}if(this.w!=this.X[E]){for(var d={},b=a=0;a<this.X[E];)c=this.X[a],l[F][sb][K](d,c)||(this.X[b++]=c,d[c]=1),a++;ma(this.X,b)}};N.get=function(a,b){return l[F][sb][K](this.Ya,a)?this.Ya[a]:b};N.set=function(a,b){l[F][sb][K](this.Ya,a)||(this.w++,this.X[t](a),this.Jd++);this.Ya[a]=b};
N.jg=function(a){var b;if(a instanceof Vd)b=a.pc(),a=a.ad();else{b=[];var c=0,d;for(d in a)b[c++]=d;c=[];d=0;for(var e in a)c[d++]=a[e];a=c}for(e=0;e<b[E];e++)this.set(b[e],a[e])};N.Ag=function(a){this.Pd();var b=0,c=this.X,d=this.Ya,e=this.Jd,f=this,i=new Ud;i.next=function(){for(;;){if(e!=f.Jd)throw da("The map has changed since the iterator was created");if(b>=c[E])throw Td;var i=c[b++];return a?i:d[i]}};return i};var Wd=function(a,b,c){this.Kb=a||j;this.Ve=b||j;this.wg=!!c};N=Wd[F];N.Hb=function(){if(!this.T&&(this.T=new Vd,this.w=0,this.Kb))for(var a=this.Kb[H]("&"),b=0;b<a[E];b++){var c=a[b][w]("="),d=j,e=j;c>=0?(d=a[b].substring(0,c),e=a[b].substring(c+1)):d=a[b];d=ga(d[u](/\+/g," "));d=this.Gb(d);this.add(d,e?ga(e[u](/\+/g," ")):"")}};N.T=j;N.w=j;N.add=function(a,b){this.Hb();this.Be();a=this.Gb(a);if(this.Jb(a)){var c=this.T.get(a);Xb(c)?c[t](b):this.T.set(a,[c,b])}else this.T.set(a,b);this.w++;return this};
N.Jb=function(a){this.Hb();a=this.Gb(a);return this.T.Jb(a)};N.pc=function(){this.Hb();for(var a=this.T.ad(),b=this.T.pc(),c=[],d=0;d<b[E];d++){var e=a[d];if(Xb(e))for(var f=0;f<e[E];f++)c[t](b[d]);else c[t](b[d])}return c};N.ad=function(a){this.Hb();if(a)if(a=this.Gb(a),this.Jb(a)){var b=this.T.get(a);if(Xb(b))return b;else a=[],a[t](b)}else a=[];else for(var b=this.T.ad(),a=[],c=0;c<b[E];c++){var d=b[c];Xb(d)?xc(a,d):a[t](d)}return a};
N.set=function(a,b){this.Hb();this.Be();a=this.Gb(a);if(this.Jb(a)){var c=this.T.get(a);Xb(c)?this.w-=c[E]:this.w--}this.T.set(a,b);this.w++;return this};N.get=function(a,b){this.Hb();a=this.Gb(a);if(this.Jb(a)){var c=this.T.get(a);return Xb(c)?c[0]:c}else return b};
la(N,function(){if(this.Kb)return this.Kb;if(!this.T)return"";for(var a=[],b=0,c=this.T.pc(),d=0;d<c[E];d++){var e=c[d],f=ic(e),e=this.T.get(e);if(Xb(e))for(var i=0;i<e[E];i++)b>0&&a[t]("&"),a[t](f),e[i]!==""&&a[t]("=",ic(e[i])),b++;else b>0&&a[t]("&"),a[t](f),e!==""&&a[t]("=",ic(e)),b++}return this.Kb=a[Ob]("")});N.Be=function(){delete this.Lg;delete this.Kb;this.Ve&&delete this.Ve.Kg};N.Gb=function(a){a=r(a);this.wg&&(a=a[Ub]());return a};var X=function(a,b){this.x=a;this.y=b};X[F].fa=function(a){var b=this.x*a.b+this.y*a.d+a.f;this.x=this.x*a.a+this.y*a.c+a.e;this.y=b};var Xd=function(a,b,c,d,e,f){this.a=a;this.b=b;this.c=c;this.d=d;this.e=e;this.f=f};N=Xd[F];N.xd=function(){var a=this.a*this.d-this.b*this.c;return new Xd(this.d/a,-this.b/a,-this.c/a,this.a/a,(this.c*this.f-this.d*this.e)/a,(this.b*this.e-this.a*this.f)/a)};
N.gg=function(a){var b=n.cos(a),a=n.sin(a);return new Xd(this.a*b-this.c*a,this.b*b-this.d*a,this.a*a+this.c*b,this.b*a+this.d*b,this.e,this.f)};N.fc=function(a,b){return new Xd(this.a*a,this.b*a,this.c*b,this.d*b,this.e,this.f)};N.translate=function(a,b){return new Xd(this.a,this.b,this.c,this.d,this.e+a,this.f+b)};la(N,function(){return"matrix("+this.a+" "+this.b+" "+this.c+" "+this.d+" "+this.e+" "+this.f+")"});
N.multiply=function(a){return new Xd(this.a*a.a+this.c*a.b,this.b*a.a+this.d*a.b,this.a*a.c+this.c*a.d,this.b*a.c+this.d*a.d,this.a*a.e+this.c*a.f+this.e,this.b*a.e+this.d*a.f+this.f)};var Yd=function(a,b,c,d,e,f,i,o){this.va=a;this.Ka=b;this.ua=c;this.Ja=d;this.ta=e;this.Ia=f;this.xa=i;this.La=o};N=Yd[F];N.Rf=function(a){return new Yd(this.va*a.va,this.va*a.Ka+this.Ka,this.ua*a.ua,this.ua*a.Ja+this.Ja,this.ta*a.ta,this.ta*a.Ia+this.Ia,this.xa*a.xa,this.xa*a.La+this.La)};
ra(N,function(a){return new Zd(a.Db*this.va+this.Ka,a.Cb*this.ua+this.Ja,a.b*this.ta+this.Ia,this.te(a.a))});N.$f=function(a,b,c){return new Zd(a*this.va+this.Ka,b*this.ua+this.Ja,c*this.ta+this.Ia,1)};N.te=function(a){return this.xa*a+this.La/255};N.Of=function(){return this.va==1&&this.Ka==0&&this.ua==1&&this.Ja==0&&this.ta==1&&this.Ia==0&&this.La==0};var $d=function(a,b,c,d){this.ve();if(O(a))this.C=a;if(O(b))this.D=b;if(O(c))this.J=c;if(O(d))this.K=d};N=$d[F];
N.ve=function(){this.C=q[ya];this.J=q.NEGATIVE_INFINITY;this.D=q[ya];this.K=q.NEGATIVE_INFINITY};N.expand=function(a){if(a.x<this.C)this.C=a.x;if(a.x>this.J)this.J=a.x;if(a.y<this.D)this.D=a.y;if(a.y>this.K)this.K=a.y};N.add=function(a){this.D+=a.D;this.K+=a.K;this.C+=a.C;this.J+=a.J};N.fa=function(a){var b=new X(this.C,this.D),c=new X(this.C,this.K),d=new X(this.J,this.D),e=new X(this.J,this.K);this.ve();b.fa(a);c.fa(a);d.fa(a);e.fa(a);this[Ca](b);this[Ca](c);this[Ca](d);this[Ca](e)};
N.Nf=function(a){return(this.C>=a.C&&this.C<=a.J||this.J>=a.C&&this.J<=a.J||a.C>=this.C&&a.C<=this.J)&&(this.D>=a.D&&this.D<=a.K||this.K>=a.D&&this.K<=a.K||a.D>=this.D&&a.D<=this.K)};N.contains=function(a,b){return a>=this.C&&a<=this.J&&b>=this.D&&b<=this.K};N.ug=function(a){this[Ca](new X(a.C,a.D));this[Ca](new X(a.C,a.K));this[Ca](new X(a.J,a.D));this[Ca](new X(a.J,a.K))};var ae=function(a,b,c,d){if(Zb(a)){var b=b==j?l[va](a):P(b)?b[H](","):b,e={};if(d&4)e.writable=h;if(d&2)e.configurable=h;if(d&1)e.enumerable=h;if(c&4)e.writable=k;if(c&2)e.configurable=k;if(c&1)e.enumerable=k;for(c=0;c<b[E];++c)(d=l[vb](a,b[c]))&&d.configurable&&l[Wa](a,b[c],e)}},be=function(){};l[Wa](be[F],"unwatch",{get:function(){return function(a){if(arguments[E]<1)return k;var b=this[a];delete this[a];this[a]=b;return h}}});
l[Wa](be[F],"watch",{get:function(){return function(a,b,c){if(arguments[E]<2)return k;for(var d=this,e=j,f=this;f[Gb];f=f[Gb])if(l[vb](f,a)!=j){d=f;e=l[vb](f,a);break}if(!e||e.configurable){var i=d[a];delete d[a];l[Wa](d,a,{get:function(){return i},set:function(d){return i=b[K](this,a,i,d,c)},configurable:h})}return h}}});var ce={};be.registerClass=function(a,b){if(arguments[E]<2)return k;ce[a]=b;return h};ae(be,j,3);var de=function(a,b,c,d,e,f,i){O(a)&&O(b)?(c=O(c)?c:1,d=O(d)?d:0,e=O(e)?e:0,f=O(f)?f:0,i=O(i)?i:0,this.Sd=new Date(a,b,c,d,e,f,i)):this.Sd=O(a)?new Date(a):new Date;if(!de[F].getDate){a=l[va](this.Sd[Gb]);for(b=0;b<a[E];b++)a[b]!="constructor"&&(de[F][a[b]]=ec(function(a,b){return this.Sd[a](b)},a[b]))}};de.UTC=Date.UTC;ae(de,j,3);var ee=function(){switch(arguments[E]){case 0:break;case 1:ma(this,arguments[0]);break;default:for(var a=0;a<arguments[E];++a)this[t](arguments[a])}};T(ee,ba);var fe=function(){},ge={},he=0,ie=0,je=[];fe.addListener=function(a){O(a)&&"onKeyUp"in a&&"onKeyDown"in a&&(sc(je,a)>=0||je[t](a))};fe.getAscii=function(){return ie};fe.getCode=function(){return he};fe.isDown=function(a){return ge[a]?h:k};fe.isToggled=function(){return k};fe.removeListener=function(a){uc(je,a)};
l[Ma](fe,{BACKSPACE:{value:8,writable:k},CAPSLOCK:{value:20,writable:k},CONTROL:{value:17,writable:k},DELETEKEY:{value:46,writable:k},DOWN:{value:40,writable:k},END:{value:35,writable:k},ENTER:{value:13,writable:k},ESCAPE:{value:27,writable:k},HOME:{value:36,writable:k},INSERT:{value:45,writable:k},LEFT:{value:37,writable:k},PGDN:{value:34,writable:k},PGUP:{value:33,writable:k},RIGHT:{value:39,writable:k},SHIFT:{value:16,writable:k},SPACE:{value:32,writable:k},TAB:{value:9,writable:k},UP:{value:38,
writable:k}});W(m,"keyup",function(a){he=a[x];ge[a[x]]=k;for(a=0;a<je[E];++a)je[a].onKeyUp()},k);W(new Md(m),"key",function(a){he=a[x];ie=a[Ua];ge[a[x]]=h;for(a=0;a<je[E];++a)je[a].onKeyDown()},k);ae(fe,j,3);var ke=function(a){this.L=a;this.Eb=[];ae(this,j,3);W(this.L.Na(),"mousedown",this.Mb,h,this);W(this.L.Na(),"mouseup",this.Nb,h,this);W(this.L.Na(),"mousemove",this.md,h,this)};N=ke[F];N.Fa=h;N.update=function(){this.L.Na()[J].cursor=this.Fa?this.L.Pc()?"pointer":this.L.ag()?"pointer":!this.L[Pb]()&&this.L.bg()?"pointer":"default":"none"};N.Mb=function(){tc(this.Eb,function(a){a.Mg()})};N.md=function(){tc(this.Eb,function(a){a.Ng()})};N.Nb=function(){tc(this.Eb,function(a){a.Og()})};
ke[F].addListener=function(a){if(O(a)){var b=this.L.l().j(a,"onMouseDown"),c=this.L.l().j(a,"onMouseMove"),d=this.L.l().j(a,"onMouseUp");b in a&&c in a&&d in a&&(sc(this.Eb,a)>=0||this.Eb[t](a))}};ke[F].hide=function(){var a=this.Fa;this.Fa=k;this[Mb]();return a};ke[F].show=function(){var a=this.Fa;this.Fa=h;this[Mb]();return a};ke[F].removeListener=function(a){uc(this.Eb,a)};ae(ke[F],j,3);var pe=function(a,b,c,d){var e=j;switch(a[C]){case 2:d=le("linearGradient",a,c);d[y]("x1",-16384);d[y]("x2",16384);e=d;break;case 3:case 4:d=le("radialGradient",a,c);d[y]("r",16384);d[y]("cx",0);d[y]("cy",0);a[hb].f&&c.lb(d,"fx",a[hb].f,function(a){return a*16384});e=d;break;case 5:case 7:if(c=d.Ca[a[Aa]])b=me(ne(a[Qb]),b[0]),e=oe(a,b,c.h[za],c.h[M],d)}if(a[hb]&&a[hb].spread)switch(a[hb].spread){case 1:e[y]("spreadMethod","reflect");break;case 2:e[y]("spreadMethod","repeat")}if(a[hb]&&a[hb].interpolation)switch(a[hb].interpolation){case 1:e[y]("color-interpolation",
"linearRGB")}if(e!=j)e.id=Sd.oa().Da();return e},le=function(a,b,c){a=m[G]("http://www.w3.org/2000/svg",a);a[y]("gradientUnits","userSpaceOnUse");b[Qb]&&c.lb(a,"gradientTransform",b[Qb],ne);for(var d=0;d<b[hb].stops[E];d++)a[s](qe(b[hb].stops[d],c));return a},qe=function(a,b){var c=m[G]("http://www.w3.org/2000/svg","stop");b.lb(c,"offset",a.offset,function(a){return a/255});b.rc(c,"stop-color",a[Na]);b.qc(c,"stop-opacity",a[Na]);return c},re=function(a,b,c,d){switch(b[C]){case 1:c.rc(a,"fill",b[Na]);
c.qc(a,"fill-opacity",b[Na]);break;case 2:case 3:case 4:a[y]("fill","url(#"+d.id+")")}};function se(a,b){this.Ge=a;this.He=b}
var me=function(a,b){function c(a,b){e.x=a;e.y=b;e.fa(d);f[t](e.x);i[t](e.y)}var d=a.xd(),e=new X(0,0),f=[],i=[];c(b[Fb],b[sa]);c(b[Jb],b[sa]);c(b[Fb],b[xa]);c(b[Jb],b[xa]);return new se(f,i)},oe=function(a,b,c,d,e){var f=m[G]("http://www.w3.org/2000/svg","g");f.id=Sd.oa().Da();var i=m[G]("http://www.w3.org/2000/svg","g"),o=m[G]("http://www.w3.org/2000/svg","g");o[s](f);o[s](i);for(var a=e.Ca[a[Aa]].ha(),p=n[Ga](n.min[L](n,b.Ge)/c),e=n.ceil(n.max[L](n,b.Ge)/c);p<e;p++){var A=m[G]("http://www.w3.org/2000/svg",
"use");A[La]("http://www.w3.org/1999/xlink","href","#"+a.id);A[y]("x",p*c);f[s](A)}c=n[Ga](n.min[L](n,b.He)/d);for(b=n.ceil(n.max[L](n,b.He)/d);c<b;c++)a=m[G]("http://www.w3.org/2000/svg","use"),a[La]("http://www.w3.org/1999/xlink","href","#"+f.id),a[y]("y",c*d),i[s](a);return o};var te=function(a,b,c,d){if(b!=j){if(b[fb]!=j)a[y]("stroke","url(#"+d.id+")");else d=b[Na]!=j?b[Na]:[0],c.rc(a,"stroke",d),c.qc(a,"stroke-opacity",d);c.lb(a,"stroke-width",b[za],function(a){return n.max(14,a)});c="round";if(b.cap!=j)switch(b.cap){case 1:c="butt";break;case 2:c="square"}a[y]("stroke-linecap",c);c="round";if(b.joint!=j)switch(b.joint){case 1:c="bevel";break;case 2:c="miter"}a[y]("stroke-linejoin",c);b.miter!=j&&a[y]("stroke-miterlimit",b.miter)}};var ue=function(){this.H={}};ue[F].eb=function(a,b){this.H[a]=b};ue[F].og=function(a){return this.H[a]?this.H[a]:j};ue[F].vf=function(a,b){this.H[a]&&this.H[a].rg(b)};var we=function(a){this.q=[];this.cf=a;this.Qc=[];this.p=new ve(this)};N=we[F];N.yb=function(a,b){a.depth=b;Cc(this.q,a,function(a,b){return a[B]-b[B]});xe(this.r,a)};N.Od=function(a){return Ac(this.q,function(a,c){return a-c[B]}||Bc,k,a)};N.Ac=function(a){a=this.Od(a);return a>=0?this.dd(a):j};N.dd=function(a,b){var c=this.q[a];b!=h&&(c.se()?(c.Va(),this.Qc[t](c)):(ye(this.r,c),c.M(),this.p.re(c)));this.q[Nb](a,1);c.depth=g;return c};N.Xe=function(a){a=this.Od(a);return a<0?j:this.dd(a,h)};
N.cg=function(a){for(var b=0;b<this.q[E];++b)if(this.q[b]==a)return this.dd(b)};N.od=function(a){a=this.Od(a);return a>=0?this.q[a]:j};N.ig=function(a){for(var b=0;b<this.q[E];++b)if(this.q[b][Ta]()==a)return this.q[b];return j};N.M=function(){for(var a=0;a<this.q[E];a++)this.dd(a)};N.Va=function(){for(var a=0;a<this.q[E];a++)this.q[a].Va()};N.dg=function(){for(var a=0;a<this.Qc[E];a++){var b=this.Qc[a];b.M();this.p.re(b);ye(this.r,b)}this.Qc=[]};
N.we=function(a){this.r=a;for(var b=0;b<this.q[E];++b)xe(a,this.q[b])};N.ic=function(a,b){this.r&&(ye(this.r,a),b&&xe(this.r,a,b))};N.Nd=function(a,b){var c=this.Xe(a),d=this.Xe(b);c&&this.yb(c,b);d&&this.yb(d,a)};var xe=function(a,b,c){a&&(O(c)||(c=b[Ta]()),c&&!a[sb](c)&&(a[c]=b.B()))},ye=function(a,b){if(a){var c=b[Ta]();c&&b.B()===a[c]&&delete a[c]}};
we[F].Xf=function(a){for(var b=0,c=0;b<this.q[E]||c<a.q[E];){var d=this.q[b],e=a.q[c],f=d?d[B]:q[ya],i=e?e[B]:q[ya];i<f?(e[zb](),this.yb(e,i),c++,b++):i>f?d.Qb()?b++:this.Ac(f):(U(f==i),U(d&&e),d.Qb()||(!d.Ma()||!e.Ma()||d.vb!=e.vb?(this.Ac(i),e[zb](),this.yb(e,i)):(d[Qa](e.O()),d.Ta(e.Aa),e.M())),b++,c++)}};var ve=function(a){this.s=a;this.Uc=[];this.cc={}};ve[F].re=function(a){this.Uc[t](a)};
ve[F].u=function(){if(!this.F)this.F=m[G]("http://www.w3.org/2000/svg","g");this.ge();for(var a=j,b=-1,c=this.s.q,d=0;d<c[E];++d){var e=c[d],f=e.p;e[B]>b&&(a=j);f.u();f.Lf(a);var i=f.ha();if(e.wb>0){var o=bc(e),p=this.cc[o];if(!O(p))p=m[G]("http://www.w3.org/2000/svg","clipPath"),p.id=f.qe(),this.cc[o]=p;ld(p);f=[];ze(i,"",f);for(i=0;i<f[E];i++)p[s](f[i]);i=p}if(this.F[bb][d]!=i)p=this.F,p.insertBefore(i,p[bb][d]||j);if(e.wb>0)a=e,b=e.wb}};ve[F].ha=function(){return this.F};
var ze=function(a,b,c){var d=a.nodeName[Ub](),b=a.hasAttribute("transform")?b?b+" "+a[Ab]("transform"):a[Ab]("transform"):b;if(d=="path"||d=="text"||d=="use")a[Ab]("fill")!="none"&&(a=a.cloneNode(h),a[y]("transform",b),c[t](a));else if(d=="g")for(d=0;d<a[bb][E];d++)ze(a[bb][d],b,c)};ve[F].ge=function(){for(var a=0;a<this.Uc[E];++a){var b=this.Uc[a],c=b.p;md(c.ha());b=bc(b);O(this.cc[b])&&(md(this.cc[b]),delete this.cc[b]);c.M()}this.Uc=[]};ve[F].Ea=function(){for(var a=this.s.q,b=0;b<a[E];++b)a[b].U(8)};var Ae=function(a){this.g=a;this.wb=0;this.ac="";this.pb=j;this.N=1;this.fb=k;this.pa=[];this.Fa=h;this.vb=0;this.je=this.ie=k;this.Lc=new Xd(1,0,0,1,0,0);this.Aa=new Yd(1,0,1,0,1,0,1,0)};N=Ae[F];N.Pa=function(a){l[Wa](a,"__swiffy_d",{value:this});l[Ma](a,Be)};N.B=function(){if(!this.r)this.r=new Ce,this.Pa(this.r);return this.r};N.ja=function(){this.Eg=h};N.Qb=function(){return!!this.Eg};N.setTransform=function(a){if(this.Lc!=a)this.U(2),this.Lc=a};N.O=function(){return this.Lc};
N.kf=function(a){U(this.wb==0);this.wb=a};N.U=function(a){a&&this.pb!=j&&this.pb.Nc();this.N|=a};N.Nc=function(){!this.fb&&this[ua]()!=j&&this[ua]().Nc();this.fb=h};N.Bc=function(a){this.vb=a};N.M=function(){this.je=h};N.Va=function(){this.ie=h};N.Ta=function(a){if(this.Aa!=a)this.U(8),this.Aa=a};N.Ga=function(){return this.p.Ga()};N.be=function(a){if(this.pa!=a)this.U(4),this.pa=a};N.hb=function(a){a=r(a);a!=this.ac&&this.pb&&this.pb.ic(this,a);this.ac=a};N.getName=function(){return this.ac};
N.Jc=function(a){this.pb=a};N.getParent=function(){return this.pb};N.sg=function(a){if(this.Fa!=a)this.U(16),this.Fa=a};N.Ma=function(){return k};N.se=function(){return k};N.ob=function(){return this.p.ob()};N.Ba=function(){};pa(N,function(){});var De=function(a){this.i=a;this.ne=this.Ra=this.Ua=this.ea=j;this.jb=new Yd(1,0,1,0,1,0,1,0);this.pa=[];this.Ob=j;this.G=[];this.ef=eval("typeof SVGFilterElement")!="undefined"};N=De[F];N.ha=function(){return this.F};N.Wc=function(a){return Ee(a,this.jb)};
N.Re=function(a){return Fe(a,this.jb)};
N.u=function(){var a=this.i.N;if(a||this.i.fb){if(a&1)a^=1,a|=8,this.F=this.Wb=this.nb();a&16&&(a^=16,this.F[y]("display",this.i.Fa?"inline":"none"));a&2&&(a^=2,this.Wb[y]("transform",this.sf()));if(a&4&&(a^=4,a|=8,this.ef)){var b="SourceGraphic";if(this.ea)this.pa=[],ld(this.ea);for(var c=0;c<this.i.pa[E];++c){var d=new Ge[this.i.pa[c][C]](this,this.i.pa[c]);if(d)this.pa[t](d),d[L](b),b=d[kb](),d=d.region,this.Ob==j?this.Ob=d:d!=j&&this.Ob.add(d)}var e=this;this.i.g.he(function(){e.tf()});this.Ua&&
(U(!!this.ea),this.ea[bb][E]>0?this.Ua[y]("filter","url(#"+this.ea.id+")"):this.Ua.removeAttribute("filter"))}a&8&&(a^=8,this.rf(),this.Ea());if(this.ea){var f=this.F;this.i.g.he(function(){f[y]("transform",f[Ab]("transform"))})}this.i.N=a}};N.sf=function(){var a=this.i.Lc[D]();O(this.rd)&&(a+=" "+this.rd);return a};
N.Lf=function(a){if(this.ne!=a){if(a){if(!this.Ra)this.Ra=m[G]("http://www.w3.org/2000/svg","g"),nd(this.Ra,this.F),this.Ra[s](this.F),this.F=this.Ra;this.Ra[y]("clip-path","url(#"+a.p.qe()+")")}else if(this.Ra==this.F){var b=this.Ra.firstChild;nd(b,this.F);this.F=b;this.Ra=j}this.ne=a}};N.qe=function(){if(!O(this.Md))this.Md=Sd.oa().Da(),this.F.id=this.Md;return this.Md};N.M=function(){this.ea!=j&&md(this.ea)};
N.ob=function(){this.i.g.u();var a=this.F.getBBox(),b=[];b[0]=new X(a.x,a.y);b[1]=new X(a.x,a.y+a[M]);b[2]=new X(a.x+a[za],a.y);b[3]=new X(a.x+a[za],a.y+a[M]);for(var a=new $d,c=0;c<b[E];++c)a[Ca](b[c]);return a};N.Ga=function(){this.i.g.u();var a;a=j;for(var b=this.F;b instanceof SVGElement;){if(b[Qb]){var c=b[Qb].baseVal.consolidate();c!=j&&(a=a!=j?c[Ea].multiply(a):c[Ea])}b=b[Lb]}return a!=j?new Xd(a.a,a.b,a.c,a.d,a.e,a.f):new Xd(1,0,0,1,0,0)};
N.wa=function(){if(this.ea==j&&(this.ea=m[G]("http://www.w3.org/2000/svg","filter"),this.ea.id=Sd.oa().Da(),this.i.g.ub[s](this.ea),this.Ua==j&&(this.Ua=m[G]("http://www.w3.org/2000/svg","g"),nd(this.Ua,this.Wb),this.Ua[s](this.Wb),this.F==this.Wb)))this.F=this.Ua;return this.ea};
N.tf=function(){if(this.Ob!=j){var a=this.Ob,b=this.F.getBBox(),c=this.wa(),d=a.J-a.C,e=a.K-a.D;if(b[za]<=0)b.width=1;if(b[M]<=0)b.height=1;d/=b[za];var f=a.D/b[M];e/=b[M];c[y]("x",a.C/b[za]-0.1);c[y]("width",1.2+d);c[y]("y",f-0.1);c[y]("height",1.2+e)}};N.rf=function(){var a=this.i[ua]();this.jb=a?a.p.jb.Rf(this.i.Aa):this.i.Aa};N.uf=function(a,b){this.G[t](function(){a[y]("opacity",this.Re(b))})};N.td=function(a,b,c){this.G[t](function(){var d=this.Wc(c);a[y](b,d);a[y](b+"-opacity",d.a)})};
N.Ea=function(){for(var a=this.G,b=0;b<a[E];++b)a[b][K](this);if(this.pa)for(b=0;b<this.pa[E];++b)this.pa[b].Ea()};var He=function(a){Ae[K](this,a);this.la=1;this.Me=k};T(He,Ae);var Ie={Xg:1,Vg:2,ah:4,Zg:8,$g:16,hh:32,Tg:64,Yg:128,Sg:256,fh:512,gh:1024,eh:2048,dh:4096,bh:8192,Ug:16384,Qg:32768,Pg:65536,Wg:131072,Rg:262144},Je={256:"onDragOver",512:"onRollOut",1024:"onRollOver",2048:"onReleaseOutside",4096:"onRelease",8192:"onPress",262144:"onDragOut"},Ke=function(a,b){l[Wa](this,a,{value:b});var c=this.__swiffy_d;c&&c.wd()},Le=function(){};N=He[F];N.wd=function(){if(!this.Me)this.U(128),this.Me=h};
N.ma=function(a){this.yd(a.la);this.Fd(a.ya)};N.Fd=function(a){var b=Je[a];b&&this.B()[b]&&this.g.l().zd(R(function(){this.B()[b]()},this));this.g.l().Ic()};N.yd=function(a){if(this.la!=a)this.la=a};N.trackAsMenu=function(){return k};N.Hf=function(){this.g.Pf(this);this.g[Pb]()==k&&this.la==1?this.ma(Me):this[Hb]()&&this.g.Pc()==k&&this.la==1?this.ma(Ne):this.g.Ad(this)&&this.la==2&&this.ma(Oe)};
N.hd=function(){this.g.Qf(this);this.g[Pb]()==k&&this.la==2?this.ma(Pe):this[Hb]()&&this.g.Pc()==k&&this.la==4?this.ma(Qe):this.g.Ad(this)&&this.la==4&&this.ma(Re)};N.Mb=function(a){this[Hb]()?this.g[Fa](this):this.g[Fa](this,h,R(this.Sf,this));a[qb]();this.ma(Se)};N.Nb=function(a){var b=this[Hb]()&&this.g.Pc()==k||this.g.Ad(this);this.g[db](this);a[qb]();b?this.ma(Te):this.ma(Me)};N.Sf=function(){this.ma(Ue)};var Ve=function(a){De[K](this,a);this.ka=[]};T(Ve,De);
Ve[F].u=function(){Ve.o.u[K](this);if(this.i.N&128){this.i.N^=128;var a=this.Mc();a[J].pointerEvents="all";var b=this.i,c;"createTouch"in m||(c=W(a,"mouseover",b.Hf,k,this.i),this.ka[t](c));c=W(a,"mouseout",b.hd,k,this.i);this.ka[t](c);c=W(a,"createTouch"in m?"touchend":"mouseup",b.Nb,k,this.i);this.ka[t](c);c=W(a,"createTouch"in m?"touchstart":"mousedown",b.Mb,k,this.i);this.ka[t](c)}};
Ve[F].ue=function(a,b,c){var d,e;if(a)d="keydown",e=function(b){return b[x]==a};else if(b)d="keypress",e=function(a){return a[Ua]==b};else return;this.ka[t](W(m,d,function(a){e(a)&&(c(),a[qb]())},h,this.i))};Ve[F].M=function(){Ve.o.M[K](this);for(var a=0;a<this.ka[E];a++)Ed(this.ka[a])};var We=function(a,b,c){this.ac=a;this.la=b;this.ya=c};We[F].getName=function(){return this.ac};
var Ne=new We("IdleToOverDown",4,256),Me=new We("IdleToOverUp",2,1024),Ue=new We("OutDownToIdle",1,2048),Oe=new We("OutDownToOverDown",4,256),Qe=new We("OverDownToIdle",1,262144),Re=new We("OverDownToOutDown",2,262144),Te=new We("OverDownToOverUp",2,4096),Pe=new We("OverUpToIdle",1,512),Se=new We("OverUpToOverDown",4,8192);var Ye=function(a,b){He[K](this,b.g);this.h=a;this.ib=b;this.q=new we(k);this.ld=new we(k);this.p=new Xe(this);this.h[mb]&&this.Cf(this.h[mb]);this.pd(this.q,1);this.pd(this.ld,8);this.wd()};T(Ye,He);N=Ye[F];N.Pa=function(a){Ye.o.Pa[K](this,a);this.q.we(a)};N.Cf=function(a){for(var b=0;b<a[E];b++){var c=a[b];c.convertedActions=this.ib.l().kb(c[mb]);if(c[x]||c.keyAscii){var d=R(this.ye,this,c);this.p.ue(c[x],c.keyAscii,d)}}};
N.yd=function(a){a!=this.la&&this.pd(this.q,a,this.la);Ye.o.yd[K](this,a);var b=this.p;setTimeout(function(){b.u()},0)};N.ye=function(a){this.oe(a);this.g.l().Ic()};N.Ff=function(a){var b=this.h[mb];if(b){for(var c=0;c<b[E];c++){var d=b[c];d[sb](a[Ta]())&&this.oe(d)}this.g.l().Ic()}};N.Je=function(){return this.ib};N.ma=function(a){var b=this.h.sounds;b&&b[sb](a[Ta]())&&this.g.zb().ke(b[a[Ta]()]);this.Ff(a);Ye.o.ma[K](this,a)};N.trackAsMenu=function(){return this.h[Hb]};
N.oe=function(a){this.ib.l().Id(new Ze(a.convertedActions,this.Je()))};N.pd=function(a,b,c){this.U(32);var d=this.h.records;if(d){if(O(c))for(var e=0;e<d[E];e++){var f=d[e],i=f[Ya]&c,o=f[Ya]&b;i&&!o&&a.Ac(f[B])}for(e=0;e<d[E];e++)if(f=d[e],i=f[Ya]&c,(o=f[Ya]&b)&&!i)i=this.ib.gd(f.id),i.Ma()&&b!=8&&i.hb(this.g.Vd()),i.Jc(this),i.Ba(),i[zb](),a.yb(i,f[B]),f[Qb]&&i[Qa](ne(f[Qb])),f[Eb]&&i.Ta($e(f[Eb]))}};N.Ma=function(){return h};N.ic=function(a,b){this.q.ic(a,b)};var Xe=function(a){Ve[K](this,a)};
T(Xe,Ve);Xe[F].nb=function(){var a=this.i.q.p;a.u();this.i.ld.p.u();this.Mc()[y]("style","visibility:hidden;");var b=m[G]("http://www.w3.org/2000/svg","g");b[s](a.ha());b[s](this.Mc());return b};Xe[F].u=function(){Xe.o.u[K](this);var a=this.i.N;if(this.i.fb||a&32)a&=-33,this.i.fb=k,this.i.q.p.u();this.i.N=a};Xe[F].Ea=function(){Xe.o.Ea[K](this);this.i.q.p.Ea();this.i.Nc()};Xe[F].Mc=function(){return this.i.ld.p.ha()};var bf=function(a,b){Ae[K](this,b.g);this.h=a;this.ib=b;this.p=new af(this);this.h[nb]&&b.g.l().Bf(this.h[nb],this,b,this.h[Ba]);this.h[Ba]&&!O(this.wc)&&this.ud(this.h[Ba])};T(bf,Ae);bf[F].ud=function(a){if(this.wc!=a)this.U(64),this.wc=a};bf[F].M=function(){bf.o.M[K](this);this.h[nb]&&this.ib.l().Kf(this.h[nb],this,this.ib)};bf[F].Ma=function(){return this.h[nb]!=g};var af=function(a){De[K](this,a)};T(af,De);
af[F].u=function(){af.o.u[K](this);if(this.i.N&64&&(this.i.N^=64,ld(this.kd),O(this.i.wc))){var a=r(this.i.wc);if(this.i.h.html)this.Af(this.kd,a,this.i.h.multiline);else{for(var b=this.kd,a=a[H](/\r\n|\r|\n/g),c=0;c<a[E];c++)if(a[c]==""){var d=m[Va]("br");b[s](d)}else{var d=m[Ia](a[c]),e=m[Va]("p");e[J].margin=0;e[s](d);b[s](e)}for(b=this.Xd;b<this.G[E];++b)this.G[b][K](this)}}};
af[F].nb=function(){var a=this.i.h,b=a.bounds,c=m[G]("http://www.w3.org/2000/svg","g");this.G=[];var d=m[G]("http://www.w3.org/2000/svg","foreignObject"),e=m[Va]("body");d[s](e);var f=m[Va]("div");this.kd=f;var i=this.i.g.Ca[a.font];if(i)f[J].fontFamily="'"+i.nd+"'";f[J].fontSize=a[M]+"px";if(a.bold)f[J].fontWeight="bold";if(a.italic)f[J].fontStyle="italic";this.fe(f[J],a[Na]);this.uf(d,a[Na]);f[J].textAlign=cf(a.align);if(a.wrap){if(!a.html)f[J].whiteSpace="pre-wrap"}else f[J].whiteSpace="nowrap";
f[J].wordWrap="break-word";if(a.selectable)f[J].pointerEvents="all";var o;f[J].textIndent=a[ta]+"px";if(a[ta]+a.leftMargin<0){var p=-(a[ta]+a.leftMargin),A=-a[ta];o=b[Fb]+30-p;d[y]("width",b[Jb]-b[Fb]-60+p);f[J].marginLeft=A+"px"}else o=b[Fb]+30,d[y]("width",b[Jb]-b[Fb]-60),f[J].marginLeft=a.leftMargin+"px";f[J].marginRight=a.rightMargin+"px";this.rd="translate("+o+" 0)";d[y]("x",0);p=m[G]("http://www.w3.org/2000/svg","rect");p[y]("x",b[Fb]-o);p[y]("y",b[sa]);p[y]("width",b[Jb]-b[Fb]);p[y]("height",
b[xa]-b[sa]);if(a.border)p[y]("stroke-width","10"),this.td(p,"fill",16777215),this.td(p,"stroke",0);else p[y]("fill-opacity",0);c[s](p);o=1.15;a.font!=g&&i&&(o=i.ce);this.lineHeight=o;o*=a[M];i=o;o+=a.leading|0;f[J].lineHeight=o+"px";f[J].paddingTop=a[M]+(i-o)*0.5+"px";d[y]("y",b[sa]+40-a[M]);d[y]("height",b[xa]-b[sa]-80+a[M]);e[s](f);c[s](d);this.Xd=this.G[E];return c};af[F].fe=function(a,b){this.G[t](function(){a.color=this.Wc(b)[D]()})};
af[F].Af=function(a,b,c){var d=this.i,e=this.lineHeight,f=d.h[M],i=d.h.leading|0,o=a,p=[];this.G[Nb](this.Xd);var A=function(a,b){var c=m[Va](a);o[s](c);o=c;p[t](f);p[t](e);p[t](b)},ca=this,a=b[u](/&nbsp;/g," ");df(a,{yf:function(a,b){switch(a){case "p":A("p",a);o[J].margin=0;var p=b[Ja]("align");if(p)o[J].textAlign=p[Rb];if(!c)o[J].display="inline";break;case "b":case "i":case "u":A(a,a);break;case "a":A(a,a);(p=b[Ja]("href"))&&o[y]("href",p[Rb]);(p=b[Ja]("target"))&&o[y]("target",p[Rb]);o[J].pointerEvents=
"all";o[J].color="inherit";o[J].textDecoration="inherit";break;case "br":case "sbr":p=m[Va]("br");o[s](p);break;case "font":A("span",a);(p=b[Ja]("color"))&&ca.fe(o[J],ef(p[Rb]));if(p=b[Ja]("face")){o[J].fontFamily=p[Rb];a:{var Tb=d.g.Ca,Sa;for(Sa in Tb)if(Tb[Sa]instanceof ff&&Tb[Sa].h[cb]==p[Rb]){e=Tb[Sa].ce;break a}e=1.15}}if(Sa=b[Ja]("size"))f=Sa[Rb]*20,o[J].fontSize=f+"px";if(p||Sa)o[J].lineHeight=e*f+i+"px"}},xf:function(a){p[p[E]-1]==a&&(p.pop(),e=p.pop(),f=p.pop(),o=o[Lb])},wf:function(a){o[s](m[Ia](a))}})};
var cf=function(a){switch(a){case 0:return"left";case 2:return"center";case 1:return"right";case 3:return"justify";default:return"left"}},df=function(a,b){var c=m[Va]("div");c.innerHTML=a;for(var d=0;d<c[bb][E];d++)gf(c[bb][d],b)},gf=function(a,b){switch(a.nodeType){case Node.ELEMENT_NODE:var c=a.nodeName[Ub]();b.yf(c,a.attributes);for(var d=0;d<a[bb][E];d++)gf(a[bb][d],b);b.xf(c);break;case Node.TEXT_NODE:b.wf(a.textContent)}};var kf=function(a,b,c){c/=256;for(var d=[],e=0;e<256;e++)d[e]=hf(jf(e/255)*b+c);a[y]("tableValues",d[Ob](" "))},lf=function(a,b,c){a[y]("slope",b);a[y]("intercept",c/255)},mf=function(a,b,c,d,e,f,i){c==e&&d==f||(c==1&&d==0?b[Lb]&&a[ub](b):(i(b,c,d),b[Lb]||a[s](b)))},nf=function(a){var b=m[G]("http://www.w3.org/2000/svg","filter");b.id=Sd.oa().Da();b[y]("x","0%");b[y]("y","0%");b[y]("width","100%");b[y]("height","100%");var c=m[G]("http://www.w3.org/2000/svg","feComponentTransfer");b[s](c);var d=m[G]("http://www.w3.org/2000/svg",
"feFuncR");d[y]("type","discrete");var e=m[G]("http://www.w3.org/2000/svg","feFuncG");e[y]("type","discrete");var f=m[G]("http://www.w3.org/2000/svg","feFuncB");f[y]("type","discrete");var i=m[G]("http://www.w3.org/2000/svg","feFuncA");i[y]("type","linear");var o=new Yd(1,0,1,0,1,0,1,0);return function(){var p=this.jb;p.Of()?(b[Lb]&&(md(b),a.removeAttribute("filter")),a[y]("opacity",p.xa)):(a.removeAttribute("opacity"),b[Lb]||(a[s](b),a[y]("filter","url(#"+b.id+")")),mf(c,d,p.va,p.Ka,o.va,o.Ka,kf),
mf(c,e,p.ua,p.Ja,o.ua,o.Ja,kf),mf(c,f,p.ta,p.Ia,o.ta,o.Ia,kf),mf(c,i,p.xa,p.La,o.xa,o.La,lf));o=p}};var pf=function(a,b){Ae[K](this,b.g);this.h=a;this.p=new of(this)};T(pf,Ae);var of=function(a){De[K](this,a);this.xb=[];this.zc=[]};T(of,De);N=of[F];N.nb=function(){this.G=[];var a=this.i,b=a.h,c=b.fillstyles;if(c)for(var d=0;d<c[E];d++)if(c[d]!=g){var e=pe(c[d],b.bounds,this,a.g);e!=j&&(this.xb[d]=e,a.g.ub[s](e))}if(c=b.linestyles)for(d=0;d<c[E];d++)c[d]!=g&&c[d][fb]!=g&&(e=pe(c[d][fb],b.bounds,this,a.g),e!=j&&(this.zc[d]=e,a.g.ub[s](e)));return this.zf()};
N.zf=function(){for(var a=this.i,b=a.h,c=m[G]("http://www.w3.org/2000/svg","g"),d=0;d<b.paths[E];d++){var e=b.paths[d],f=m[G]("http://www.w3.org/2000/svg","path");this.lb(f,"d",e[v],qf);f.onclick=function(){};c[s](f);if(e.line!=j&&b.linestyles!=j){var i=b.linestyles[e.line];te(f,i,this,i[fb]?this.zc[e.line]:j)}if(e[fb]!=j)if(i=b.fillstyles[e[fb]],i[Aa]==j)re(f,i,this,this.xb[e[fb]]);else{var o=m[G]("http://www.w3.org/2000/svg","clipPath");o.id=Sd.oa().Da();o[s](f);a.g.ub[s](o);f=m[G]("http://www.w3.org/2000/svg",
"g");f[y]("clip-path","url(#"+o.id+")");c[s](f);o=m[G]("http://www.w3.org/2000/svg","use");if(i[C]==5||i[C]==7)U(this.xb[e[fb]].id!=j),o[La]("http://www.w3.org/1999/xlink","href","#"+this.xb[e[fb]].id);else o[La]("http://www.w3.org/1999/xlink","href","#"+a.g.Ca[i[Aa]].ha().id);i[Qb]&&o[y]("transform",ne(i[Qb])[D]());f[s](o);this.G[t](nf(f))}else f[y]("fill","none")}return c};N.lb=function(a,b,c,d){U(c[E]==1);c=c[0];if(c instanceof Zd||c instanceof Xd)c=c[D]();a[y](b,d?d[K](this,c):c)};
N.rc=function(a,b,c){U(c[E]==1);this.G[t](function(){a[y](b,this.Wc(c[0]))})};N.qc=function(a,b,c){U(c[E]==1);this.G[t](function(){a[y](b,this.Re(c[0]))})};N.M=function(){of.o.M[K](this);for(var a=0;a<this.xb[E];a++)md(this.xb[a]);for(a=0;a<this.zc[E];a++)md(this.zc[a])};var rf=function(a,b){this.Jf=a;this.If=b};rf[F].qb=function(){return 0};var sf=function(a,b,c,d){rf[K](this,a,b);this.z=c;this.Z=d};T(sf,rf);sf[F].qb=function(a){return this.z+(this.Z-this.z)*a};var tf=function(a,b,c,d){rf[K](this,a,b);this.z=c;this.Z=d};T(tf,rf);tf[F].qb=function(a){return(new Xd(this.z.a+(this.Z.a-this.z.a)*a,this.z.b+(this.Z.b-this.z.b)*a,this.z.c+(this.Z.c-this.z.c)*a,this.z.d+(this.Z.d-this.z.d)*a,this.z.e+(this.Z.e-this.z.e)*a,this.z.f+(this.Z.f-this.z.f)*a))[D]()};
var uf=function(a,b,c,d){rf[K](this,a,b);this.z=c;this.Z=d};T(uf,rf);uf[F].qb=function(a,b){return b.$f(this.z.Db+(this.Z.Db-this.z.Db)*a,this.z.Cb+(this.Z.Cb-this.z.Cb)*a,this.z.b+(this.Z.b-this.z.b)*a)[D]()};var vf=function(a,b,c,d){rf[K](this,a,b);this.z=c;this.Z=d};T(vf,rf);vf[F].qb=function(a,b){return b.te(this.z+(this.Z-this.z)*a)};var wf=function(a,b,c,d){rf[K](this,a,b);this.$e=c[H](" ");this.af=d[H](" ");U(this.$e[E]==this.af[E])};T(wf,rf);
wf[F].qb=function(a){for(var b="",c=this.$e,d=this.af,e=0;e<c[E];e++){var f=fa(c[e],10);isNaN(f)?(U(c[e]==d[e]),b+=c[e]+" "):b+=f+(fa(d[e],10)-f)*a+" "}return b};var yf=function(a,b){pf[K](this,a,b);this.p=new xf(this)};T(yf,pf);yf[F].Bc=function(a){a!=this.vb&&this.U(256);yf.o.Bc[K](this,a)};var xf=function(a){of[K](this,a);this.ec=[]};T(xf,of);N=xf[F];N.nb=function(){return xf.o.nb[K](this)};
N.lb=function(a,b,c,d){if(c[E]==1)xf.o.lb[K](this,a,b,c,d);else U(c[E]==2),this.Kd(a,b,d?d[K](this,c[0]):c[0],d?d[K](this,c[1]):c[1])};N.rc=function(a,b,c){c[E]==1?xf.o.rc[K](this,a,b,c):this.Kd(a,b,Ee(c[0]),Ee(c[1]),uf)};N.qc=function(a,b,c){c[E]==1?xf.o.qc[K](this,a,b,c):this.Kd(a,b,Fe(c[0]),Fe(c[1]),vf)};N.Kd=function(a,b,c,d,e){var f=e;e||(c instanceof Xd?f=tf:typeof c=="number"?f=sf:(U(b=="d"),f=wf));c=new f(a,b,c,d);a[y](b,c.qb(this.i.vb/65535,this.jb));this.ec[t](c)};
N.u=function(){this.i.N&8&&(this.i.N|=256);xf.o.u[K](this);if(this.i.N&256){this.i.N^=256;for(var a=this.i.vb/65535,b=0;b<this.ec[E];b++){var c=this.ec[b].Jf,d=this.ec[b].If,e=this.ec[b].qb(a,this.jb);c[y](d,e)}}};var Af=function(a,b){Ae[K](this,b.g);this.h=a;this.p=new zf(this)};T(Af,Ae);var zf=function(a){De[K](this,a)};T(zf,De);
zf[F].nb=function(){this.G=[];var a=m[G]("http://www.w3.org/2000/svg","g"),b=this.i.h;this.rd=ne(b[Ea])[D]();this.i.U(2);for(var c=0;c<b.records[E];c++){var d=b.records[c],e=m[G]("http://www.w3.org/2000/svg","text");e[s](m[Ia](d[Ba]));var f=this.i.g.Ca[d.font];f&&e[y]("font-family","'"+f.nd+"'");e[y]("font-size",d[M]);d.bold&&e[y]("font-weight","bold");d.italic&&e[y]("font-style","italic");e[y]("x",Bf(d.x));e[y]("y",d.y);e[y]("fill-rule","nonzero");e[y]("style","white-space:pre");e[y]("unicode-bidi",
"bidi-override");this.td(e,"fill",d[Na]);a[s](e)}return a};var Cf=function(){};Cf[F].rg=function(a){this.jh=a};Cf[F].ng=function(a){return this.Lb(a)};var Df=function(a){He[K](this,a);this.s=new we(k)};T(Df,He);N=Df[F];N.vc=function(a,b){this.U(32);a[ua]()!=j&&a[ua]()[ub](a);a.Jc(this);this.s.yb(a,b)};N.removeChild=function(a){this.U(32);this.s.cg(a);a.Jc(j)};N.Rb=function(a){this.U(32);(a=this.s.Ac(a))&&a.Jc(j)};N.Pa=function(a){Df.o.Pa[K](this,a);this.s.we(a)};N.ic=function(a,b){this.s.ic(a,b)};N.B=function(){if(!this.r)this.r=new Ef,this.Pa(this.r);return this.r};N.Nd=function(a,b){this.U(32);this.s.Nd(a,b)};var Ff=function(a){Ve[K](this,a)};
T(Ff,Ve);Ff[F].u=function(){if((this.i.N&1||this.i.N&2)&&this.i.wb>0)for(var a=this.i.s.q,b=0;b<a[E];++b)a[b].U(2);Ff.o.u[K](this);a=this.i;b=a.N;if(a.fb||b&32)b&=-33,a.fb=k,a.s.p.u();a.N=b};Ff[F].Ea=function(){Ff.o.Ea[K](this);this.i.s.p.Ea();this.i.Nc()};Ff[F].M=function(){Ff.o.M[K](this);this.i.s.p.ge()};var Hf=function(a){var b=function(b){b instanceof Ce||(b=a.l().Yf(r(b)));this.r=b;this.xe=0};l[Ma](b[F],Gf);return b},Gf={getRGB:{value:function(){return this.xe}},setRGB:{value:function(a){if(this.r)this.xe=a,this.r.__swiffy_d.Ta(new Yd(0,(a&16711680)>>16,0,(a&65280)>>8,0,a&255,1,0)),this.r.__swiffy_d.ja()}},setTransform:{value:function(a){if(this.r&&a){var b=this.r.__swiffy_d,c=b.g.l().j(a,"ra"),d=b.g.l().j(a,"rb"),e=b.g.l().j(a,"ga"),f=b.g.l().j(a,"gb"),i=b.g.l().j(a,"ba"),o=b.g.l().j(a,"bb"),
p=b.g.l().j(a,"aa"),b=b.g.l().j(a,"ab");this.r.__swiffy_d.Ta(new Yd(a[c]/100,a[d],a[e]/100,a[f],a[i]/100,a[o],a[p]/100,a[b]));this.r.__swiffy_d.ja()}}},getTransform:{value:function(){if(!this.r)return j;var a=this.r.__swiffy_d.Aa;return{ra:a.va*100,rb:a.Ka,ga:a.ua*100,gb:a.Ja,ba:a.ta*100,bb:a.Ia,aa:a.xa*100,ab:a.La}}}};var Jf=function(a,b,c){Df[K](this,b);this.h=a;this.Tb={};this.xc={};this.P=-1;this.Ab=a.frameCount;this.Cc=k;this.qa=0;this.H=c;this.jd={};this.Sa=b.Sa;this.Wd=this.ae=k;this.df=[];this.Pb={};this.mb={};this.p=new If(this);this.g.qf(this)};T(Jf,Df);N=Jf[F];
N.pg=function(){if(!this.Wd){for(var a=0;a<this.h.tags[E];a++){var b=this.h.tags[a];switch(b[C]){case 10:var c=new Kf(b);this.H.eb(b.id,c);break;case 13:c=new Lf(b);this.H.eb(b.id,c);break;case 5:c=new ff(b);this.g.Ca[b.id]=c;break;case 8:c=new Mf(b);this.g.Ca[b.id]=c;break;case 1:c=new Nf(b);this.H.eb(b.id,c);break;case 17:c=new Of(b);this.H.eb(b.id,c);break;case 11:c=new Pf(b);c.vd(this.zb());break;case 7:c=new Qf(b,this.g,this.H);this.H.eb(b.id,c);break;case 6:c=new Rf(b);this.H.eb(b.id,c);break;
case 9:c=new Sf(b,this.l());this.Yb(this.qa,c);break;case 20:this.xc[this.qa]||(this.xc[this.qa]=[]);this.xc[this.qa][t](b);break;case 18:this.g.Gg.Hg(j);break;case 19:var b=b.references,d;for(d in b)c=q(d),this.H.vf(c,b[c]);break;case 15:this.jd[b.label]=this.qa;break;case 3:c=new Tf(b);this.Yb(this.qa,c);break;case 4:c=new Uf(b);this.Yb(this.qa,c);break;case 2:this.qa++;break;case 12:c=new Vf(b);this.Yb(this.qa,c);break;case 16:c=new Wf(b),this.Yb(this.qa,c)}}this.Wd=h}};
N.Ba=function(){this.pg();this.Ie();this.bc(128);this.Ub||this.Pe()};pa(N,function(){if(!this.ae)this.ae=h,this[Za](),this.Fe(k),this.Ub&&this.Pe()});N.Zb=function(a){if(a=this.mb[a])for(var b=0;b<a[E];++b)this.l().Xc(a[b])};N.bc=function(a){if(a=this.mb[a])for(var b=0;b<a[E];++b)this.l().Id(a[b])};N.se=function(){return this.mb!=g&&this.mb[32]!=g};
N.ff=function(a,b,c,d){for(var e in Ie){var f=Ie[e];a&f&&(this.mb[f]||(this.mb[f]=[]),this.mb[f][t](new Ze(d,this)),f>=256&&f<=8192&&this.wd(),f&131072&&(f=R(this.bc,this,131072),this.p.ue(b,c,f)))}};N.gd=function(a){return(a=this.H.og(a))?a.ng(this):j};N.Je=function(){return this};N.Pa=function(a){Jf.o.Pa[K](this,a);l[Ma](a,Xf)};N.M=function(){this.g.Mf(this);this.s.M();Jf.o.M[K](this)};N.Va=function(){this.ie||(this.s.Va(),this.bc(32));Jf.o.Va[K](this)};
N.Yb=function(a,b){this.Tb[a]||(this.Tb[a]=[]);this.Tb[a][t](b)};N.play=function(){this.Cc=h};N.Tf=function(){this.s.dg();this.Cc?this.Fe(h):this.Dd()};N.Fe=function(a){var b=this.P+1;b>=this.Ab&&(b=0);(this.Ab!=0||this.g.ca!=this)&&this.Rc(b,a)};N.Fd=function(a){this.bc(a);Jf.o.Fd[K](this,a)};N.Dd=function(){this.bc(64);this.l().zd(R(function(){this.B().onEnterFrame()},this))};N.Pe=function(){this.l().zd(R(function(){this.B().onLoad()},this))};N.stop=function(){this.Cc=k};
N.oc=function(a,b){a>=0&&a<this.Ab?this.Rc(a):this.P=this.Ab+1;this.Cc=b};N.$b=function(a){var b=g;typeof a=="string"&&this.jd[a]!=g?b=this.jd[a]:(a=q(a)-1,a>=0&&a==n[Ga](a)&&(b=a));return b};N.Gf=function(a){return this.Tb[a]};
N.Rc=function(a,b){var c=k,d=this.s;if(a<this.P)c=h,this.s=new we(h),this.P=-1;for(a==this.P&&b&&this.Dd();this.P<a;){this.P++;this.P==a&&b&&this.Dd();this.Wf(this.P);var e=this.Tb[this.P];if(e)for(var f=0;f<e[E];f++)e[f].kc(this),this.P==a&&e[f].jc(this)}e=this.df[this.P];Q(e)&&e();if(c)d.Xf(this.s),this.s=d};N.Wf=function(a){for(a=this.xc[a];a&&a[E]>0;){var b=this.l(),c=a[wa](),c=b.kb(c[mb]);b.Xc(new Ze(c,this))}};N.Ue=function(){this.P>0&&this.Rc(this.P-1);this[gb]()};
N.Te=function(){this.P+1<this.Ab&&this.Rc(this.P+1);this[gb]()};N.l=function(){return this.g.l()};N.zb=function(){return this.g.zb()};N.Na=function(){return this.g.Na()};N.qg=function(a,b){this.B()[a]=b};N.setCapture=function(a,b,c){this.g[Fa](a,b,c)};N.releaseCapture=function(a){this.g[db](a)};N.duplicate=function(a,b,c){var d=new Jf(this.h,this.g,this.H);d.Ub=h;d.hb(b);d[Qa](this.O());d.Ba();d[zb]();a.vc(d,c);d.Ta(this.Aa);return d};N.B=function(){this.r||this.Ie();return this.r};
N.Ie=function(){var a=Y;if(this.h.id){var b=ce[this.g.Td[this.h.id]];b!=j&&(a=b)}this.r=l[jb](a[F]);this.Pa(this.r);a[L](this.r);this.g.ca==this&&(this.r.$version=this.g.Df())};N.Ma=function(){return h};var If=function(a){Ve[K](this,a)};T(If,Ff);
If[F].nb=function(){var a=this.i,b=a.s.p;b.u();var b=b.ha(),c=ec(a.Zb,1),c=W(m,"keyup",c,k,a);this.ka[t](c);c=ec(a.Zb,2);c=W(m,"keydown",c,k,a);this.ka[t](c);c=ec(a.Zb,4);c=W(a.g.Na(),"createTouch"in m?"touchend":"mouseup",c,k,a);this.ka[t](c);c=ec(a.Zb,8);c=W(a.g.Na(),"createTouch"in m?"touchstart":"mousedown",c,k,a);this.ka[t](c);c=ec(a.Zb,16);c=W(a.g.Na(),"createTouch"in m?"touchmove":"mousemove",c,k,a);this.ka[t](c);return b};If[F].Mc=function(){return this.ha()};var Yf=function(){this.Ye=[];this.fd=[]};Yf[F].vd=function(a,b){this.Ye[a]=b};Yf[F].ke=function(a){this.fd[a]=new Audio(this.Ye[a]);this.fd[a][Za]()};Yf[F].mg=function(){for(var a in this.fd)this.fd[a].pause()};var bg=function(a,b){this.sd=k;this.yc=new X(0,0);this.Ca={};this.Gc=[];this.sa=m[G]("http://www.w3.org/1999/xhtml","div");this.sa[y]("style","position:relative;");a[s](this.sa);this.lf=new Yf;this.Bb=m[G]("http://www.w3.org/2000/svg","svg");this.$d=b[yb][Jb];this.Zd=b[yb][xa];this.jf=b.v;var c="fill-rule:evenodd;";c+="pointer-events:none;";c+="width:"+this.$d/20+"px;";c+="height:"+this.Zd/20+"px;";b.backgroundColor!=g&&(c+="background:"+Ee(b.backgroundColor)[D]());this.Bb[y]("style",c);this.Bb[y]("viewBox",
b[yb][Fb]+" "+b[yb][sa]+" "+b[yb][Jb]+" "+b[yb][xa]);this.sa[s](this.Bb);this.Fg=b[yb][Jb]/b[yb][xa];c=new ue;this.Ec=new Zf(b.frameRate,this);c.eb(0,new Qf(b,this,c));this.Sa=b.version;this.ca=new Jf(b,this,c);this.Dc=new $f(this.ca);this.Oa=j;this.qd=k;this.Fc=j;this.Ud={};this.Td={};this.Xb=new ke(this);this.mf=new ag(this);this.pf=1;this.Qa={};this.Qa.w=0;W(this.sa,"mousedown",this.Mb,k,this);W(this.sa,"mouseup",this.Nb,k,this);W(this.sa,"mouseout",this.hd,k,this);"createTouch"in m||W(this.sa,
"mousemove",this.md,k,this);W(m,"mousedown",this.gf,k,this);W(m,"mouseup",this.hf,k,this);W(this.sa,"touchstart",this.of,k,this);W(this.sa,"touchmove",this.nf,k,this);this.ca.Ba();this.ub=m[G]("http://www.w3.org/2000/svg","defs");for(var d in this.Ca)this.ub[s](this.Ca[d].Ba());d=aa.location.search+aa.location.hash;c=d[w]("?");c>=0&&this.ee(d[Da](c+1));this.ca.p.u();this.Bb[s](this.ub);this.Bb[s](this.ca.p.ha())},cg="swiffy.Stage"[H]("."),dg=Vb;!(cg[0]in dg)&&dg.execScript&&dg.execScript("var "+cg[0]);
for(var eg;cg[E]&&(eg=cg[wa]());)!cg[E]&&O(bg)?dg[eg]=bg:dg=dg[eg]?dg[eg]:dg[eg]={};N=bg[F];N.Mb=function(a){a[qb]();this[Fa](this)};N.Nb=function(a){a[qb]();this[db](this)};N.gf=function(){this[Fa](this,h)};N.hf=function(){this[db](this)};N.hd=function(a){this[Pb]()&&a[wb]==this.sa&&this[Fa](this)};N.md=function(a){this.Qd(a)};N.of=function(a){var b=a.ya.touches;b[E]==1&&(this.Qd(b[0]),a[Ka]())};N.nf=function(a){var b=a.ya.touches;b[E]==1&&(this.Qd(b[0]),a[Ka]())};
N.Qd=function(a){var b;b=this.Bb;var c=0,d=0;if(b.offsetParent){do c+=b.offsetLeft,d+=b.offsetTop;while(b=b.offsetParent)}b=[c,d];this.yc.x=a.clientX-b[0];this.yc.y=a.clientY-b[1]};N.bg=function(){return this.Qa.w>0};N.Pf=function(a){a=bc(a);a in this.Qa||(this.Qa[a]=h,this.Qa.w++);this.Xb[Mb]()};N.Qf=function(a){a=bc(a);a in this.Qa&&(delete this.Qa[a],this.Qa.w--);this.Xb[Mb]()};N.isCaptured=function(){return this.Oa!=j};N.Pc=function(){return this.Oa!=j&&this.qd};
N.Ad=function(a){return this.Oa==a};N.ag=function(){return this.Oa?bc(this.Oa)in this.Qa:k};N.setCapture=function(a,b,c){this[db](a);this.Oa=a;m.fg=function(){return k};if(b)this.qd=h;if(c)this.Fc=c,this.Xb[Mb]()};N.releaseCapture=function(a){if(this.Oa)this.Xb[Mb](),m.fg=j,this.Oa!=a&&this.Fc&&this.Fc(),this.Oa=this.Fc=j,this.qd=k};pa(N,function(){this.ca[Za]();this.Ec[zb]()});pa(bg[F],bg[F][zb]);N=bg[F];N.qf=function(a){this.Ec.Rd(a)};N.Mf=function(a){this.Ec.yg(a)};N.l=function(){return this.Dc};
N.zb=function(){return this.lf};N.Rd=function(a){this.Ec.Rd(a)};N.Na=function(){return this.sa};N.ee=function(a){for(var a=new Wd(a),b=a.pc(),c=0;c<b[E];c++){var d=b[c];this.ca.qg(d,a.get(d))}};bg[F].setFlashVars=bg[F].ee;bg[F].Vd=function(){return"instance"+this.pf++};bg[F].he=function(a){this.Gc[t](a)};bg[F].Df=function(){return"Swiffy "+this.jf};bg[F].u=function(){if(!this.sd){this.sd=h;this.ca.p.u();for(var a=0;a<this.Gc[E];a++)this.Gc[a]();this.Gc=[];this.sd=k}};var Zd=function(a,b,c,d){this.Db=a;this.Cb=b;this.b=c;this.a=d};la(Zd[F],function(){return"rgb("+this.Db.toFixed()+","+this.Cb.toFixed()+","+this.b.toFixed()+")"});
var ne=function(a){var b=0,c=fg(function(){return a[Db](b++)});return new Xd(c()/1E3+1,c()/1E3,c()/1E3,c()/1E3+1,c(),c())},Bf=function(a){for(var b=0,c=gg(function(){return a[Db](b++)}),d=[],e=0;b<a[E];)e+=fa(c(),10),d[t](e);return d[Ob](" ")},gg=function(a){return function(){var b=a();if(b==58)return 0;for(var c="";b>=48&&b<=57;)c+=r.fromCharCode(b),b=a();return(b>=97?b-96:-(b-64))+c}},fg=function(a){var b=gg(a);return function(){return fa(b(),10)}},qf=function(a){for(var b=0,c=a[w](":"),d=c+1,e=
gg(function(){return a[Db](d++)}),f="",i;b<c;)switch(i=a.charAt(b++),f[E]>0&&(f+=" "),f+=i+" ",i){case "q":f+=e()+" "+e()+" ";case "l":case "m":f+=e()+" ";case "h":case "v":f+=e();break;default:return""}return f},$e=function(a){var b=0,c=fg(function(){return a[Db](b++)});return new Yd((c()+256)/256,c(),(c()+256)/256,c(),(c()+256)/256,c(),(c()+256)/256,c())},Ee=function(a,b){var c=a,d=c&255;c>>=8;var e=c&255;c>>=8;var f=c&255;c>>=8;c=(255-(c&255))/255;b&&(d=d*b.va+b.Ka,e=e*b.ua+b.Ja,f=f*b.ta+b.Ia,
c=c*b.xa+b.La/255);return new Zd(d,e,f,c)},Fe=function(a,b){var c=a;c>>=24;c=(255-(c&255))/255;b&&(c=c*b.xa+b.La/255);return c},ef=function(a){a=a[u](/^ *rgb *\( *([^,]+) *, *([^,]+) *, *([^,]+) *\) *$/,function(a,c,d,e){return c+(d<<8)+(e<<16)});a=a[u](/^ *#([0-9a-fA-F]+) *$/,function(a,c){var d=fa(c,16);return(d&255)<<16|d&65280|(d&16711680)>>16});return a|0},hf=function(a){return a<=0.04045?a/12.92:n.pow((a+0.055)/1.055,2.4)},jf=function(a){return a<=0.0031308?a*12.92:n.pow(a,1/2.4)*1.055-0.055},
hg=function(a,b){var c=new X(b.x*20,b.y*20);c.fa(a.xd());c.x/=20;c.y/=20;return c},ig=function(a,b){var c=a.g.l().Xa(b);if(!isNaN(c))return c},jg=function(a,b,c,d){if(c[w]("_level")!=0&&b[Ub]()[w]("fscommand:")!=0)switch(c==""&&(c="_self"),d){case 0:aa.open(b,c);break;case 1:case 2:var e=jd("form");e.acceptCharset="utf-8";e.method=d==1?"get":"post";for(var f in a)f.charAt(0)!="$"&&(d=jd("input",{type:"hidden",name:f,value:a[f]}),e[s](d));e.action=b;na(e,c);e.submit();break;default:aa.open(b,c)}};var kg=function(a){this.p=a;this.Vf=Sd.oa().Da();this.region=new $d(0,0,0,0);this.G=[]},Ge=[];N=kg[F];ra(N,function(){});N.result=function(){return this.Vf};N.Se=function(a,b,c,d,e){var f=1;switch(a){case 1:f=5;break;case 2:f=3;break;case 3:f=2}a=b*20/f;c=c*20/f;f=m[G]("http://www.w3.org/2000/svg","feGaussianBlur");O(d)&&f[y]("in",d);O(e)&&f[y]("result",e);f[y]("stdDeviation",a+" "+c);this.wa()[s](f);d=new $d;d[Ca](new X(-a*3,-c*3));d[Ca](new X(+a*3,+c*3));return d};
N.Sc=function(a,b,c,d,e,f,i){var o=m[G]("http://www.w3.org/2000/svg","feComponentTransfer");O(f)&&o[y]("in",f);O(i)&&o[y]("result",i);O(e)||(e="linear");f=["feFuncR","feFuncG","feFuncB","feFuncA"];a=[a,b,c,d];for(b=0;b<4;++b){var c=j,p;for(p in a[b])c==j&&(c=m[G]("http://www.w3.org/2000/svg",f[b]),c[y]("type",e)),c[y](p,a[b][p]);c&&o[s](c)}this.wa()[s](o);return o};
N.Gd=function(a,b){var c=this.Sc({ze:0},{ze:0},{ze:0},{Ig:0});this.G[t](function(){for(var d=this.p.Wc(a),e=0;e<c[bb][E];++e){var f=c[bb][e];switch(f.localName){case "feFuncR":f[y]("intercept",hf(d.Db/255));break;case "feFuncG":f[y]("intercept",hf(d.Cb/255));break;case "feFuncB":f[y]("intercept",hf(d.b/255));break;case "feFuncA":f[y]("slope",d.a*b)}}})};
N.za=function(a,b,c,d,e){var f=m[G]("http://www.w3.org/2000/svg","feComposite");O(e)&&f[y]("result",e);O(b)&&f[y]("in",b);O(c)&&f[y]("in2",c);f[y]("operator",a);if(O(d))for(var i in d)f[y](i,d[i]);this.wa()[s](f)};N.Zf=function(a){var b=m[G]("http://www.w3.org/2000/svg","feFlood");O(a)&&b[y]("result",a);this.wa()[s](b)};
N.tg=function(a,b,c,d){var e=n.cos(a)*b*20,a=n.sin(a)*b*20,b=m[G]("http://www.w3.org/2000/svg","feOffset");O(c)&&b[y]("in",c);O(d)&&b[y]("result",d);b[y]("dx",e);b[y]("dy",a);this.wa()[s](b);return new $d(e,a,e,a)};N.Hd=function(a,b,c,d,e,f){this.Sc({slope:0},{slope:0},{slope:0},{},"linear",a);a=this.Se(b,c,d);f!=0&&this.region.ug(this.tg(e,f));this.region.add(a)};N.Yc=function(){return Sd.oa().Da()};N.wa=function(){return this.p.wa()};N.Ea=function(){for(var a=this.G,b=0;b<a[E];++b)a[b][K](this)};var lg=function(a,b){kg[K](this,a);this.tc=b[Ea];this.tc[4]/=255;this.tc[9]/=255;this.tc[14]/=255;this.tc[19]/=255};T(lg,kg);Ge[3]=lg;
ra(lg[F],function(a){for(var b=[],c=[],d=0;d<256;d++)b[d]=jf(d/255),c[d]=hf(d/255);var e={tableValues:b[Ob](" ")},c={tableValues:c[Ob](" ")},b=this.Yc(),d=this.Yc();this.Sc(e,e,e,e,"discrete",a,b);a=this.wa();e=m[G]("http://www.w3.org/2000/svg","feColorMatrix");e[y]("in",b);e[y]("result",d);e[y]("type","matrix");e[y]("values",this.tc[Ob](" "));a[s](e);this.Sc(c,c,c,c,"discrete",d,this[kb]())});var mg=function(a,b){kg[K](this,a);this.lc=b};T(mg,kg);Ge[2]=mg;ra(mg[F],function(a){var b=this.lc;this.region=this.Se(b[Sb],b.x,b.y,a,this[kb]())});var ng=function(a,b){kg[K](this,a);this.lc=b};T(ng,kg);Ge[1]=ng;ra(ng[F],function(a){this.G=[];var b=this.lc,c=this.wa();b[lb]&&this.Zf("black");this.Hd(a,b[Sb],b.x,b.y,b.angle,b.distance);b[lb]&&this.za("arithmetic",g,"black",{k2:-1,k3:1});this.Gd(b[Na],b.strength);c[xb][y]("result","shadow");!b[lb]&&!b[Ra]&&!b.hideObject?this.za("over",a,"shadow"):b[lb]&&!b[Ra]&&!b.hideObject?this.za("atop","shadow",a):!b[lb]&&b[Ra]?this.za("out","shadow",a):b[lb]&&this.za("in","shadow",a);c[xb][y]("result",this[kb]())});var og=function(a,b){kg[K](this,a);this.lc=b};T(og,kg);Ge[4]=og;
ra(og[F],function(a){this.G=[];var b=this.lc,c=this.wa(),d=this.Yc(),e=this.Yc();this.Hd(a,b[Sb],b.x,b.y,b.angle,-b.distance);this.Gd(b.highlight,b.strength);c[xb][y]("result",e);this.Hd(a,b[Sb],b.x,b.y,b.angle,b.distance);this.Gd(b.shadow,b.strength);c[xb][y]("result",d);this.za("xor",d,e,{},"shadow");b[Ra]?b[lb]?this.za("in","shadow",a):b.onTop||this.za("out","shadow",a):b[lb]?this.za("atop","shadow",a):b.onTop?this.za("over","shadow",a):this.za("over",a,"shadow");c[xb][y]("result",this[kb]())});var Kf=function(a){this.h=a};T(Kf,Cf);Kf[F].Lb=function(a){return new Ye(this.h,a)};var Lf=function(a){this.h=a};T(Lf,Cf);Lf[F].Lb=function(a){return new bf(this.h,a)};var ff=function(a){this.h=a;this.nd=Sd.oa().Da()};ff[F].ha=function(){return this.Fb};
ff[F].Ba=function(){var a;a=this.h.emSquareSize?this.h.emSquareSize:1024;var b,c,d;this.h.ascent&&this.h.descent?(b=this.h.ascent,c=this.h.descent,d=(b+c)/a):(this.h[cb]&&!this.h[rb]?(b=m[G]("http://www.w3.org/1999/xhtml","div"),b[J].fontFamily=this.h[cb],b[J].fontSize="1024px",b.innerHTML="A",m[tb][s](b),d=b.clientHeight/1024,md(b)):d=1.15,b=a*0.9,c=a*(d-0.9));this.ce=d;d=m[G]("http://www.w3.org/2000/svg","font-face");d[y]("units-per-em",a);d[y]("ascent",b);d[y]("descent",c);b="'"+this.nd+"'";this.h[cb]&&
(b+=",'"+this.h[cb]+"'");d[y]("font-family",b);d[y]("font-weight",this.h.bold?"bold":"normal");d[y]("font-style",this.h.italic?"italic":"normal");if(this.h[cb]&&!this.h[rb])a=m[G]("http://www.w3.org/2000/svg","font-face-src"),b=m[G]("http://www.w3.org/2000/svg","font-face-name"),b[y]("name",this.h[cb]),a[s](b),d[s](a),this.Fb=d;else{b=m[G]("http://www.w3.org/2000/svg","font");b[y]("horiz-adv-x",a);b[s](d);if(this.h[rb])for(a=0;a<this.h[rb][E];a++)d=this.h[rb][a],c=m[G]("http://www.w3.org/2000/svg",
"glyph"),c[y]("d",qf(d[v])),c[y]("unicode",d.unicode),d.advance&&c[y]("horiz-adv-x",d.advance),b[s](c);this.Fb=b}return this.Fb};var Mf=function(a){this.h=a};Mf[F].ha=function(){return this.Fb};
Mf[F].Ba=function(){var a=m[G]("http://www.w3.org/2000/svg","image");a.id=Sd.oa().Da();a[y]("width",this.h[za]);a[y]("height",this.h[M]);if(this.h.mask){var b=this.h[za],c=this.h[M],d=m[Va]("canvas");d.width=this.h[za];d.height=this.h[M];var e=new Image,f=new Image,i=k,o=k,p=function(){if(i&&o){var p=d.getContext("2d");p.clearRect(0,0,b,c);p.drawImage(e,0,0,b,c);p.globalCompositeOperation="xor";p.drawImage(f,0,0,b,c);a[La]("http://www.w3.org/1999/xlink","href",d.toDataURL("image/png"))}};e.onload=
function(){i=h;p()};f.onload=function(){o=h;p()};e.src=this.h[v];f.src=this.h.mask}else a[La]("http://www.w3.org/1999/xlink","href",this.h[v]);return this.Fb=a};var Of=function(a){this.h=a};T(Of,Cf);Of[F].Lb=function(a){return new yf(this.h,a)};var Nf=function(a){this.h=a};T(Nf,Cf);Nf[F].Lb=function(a){return new pf(this.h,a)};var Pf=function(a){this.h=a};Pf[F].vd=function(a){a.vd(this.h.id,this.h[v])};var Qf=function(a,b,c){this.h=a;this.L=b;this.H=c};T(Qf,Cf);Qf[F].Lb=function(){return new Jf(this.h,this.L,this.H)};var Rf=function(a){this.h=a};T(Rf,Cf);Rf[F].Lb=function(a){return new Af(this.h,a)};var Sf=function(a,b){this.Jg=a;this.Ne=b.kb(a[mb]);this.Dc=b};Sf[F].kc=function(){};Sf[F].jc=function(a){this.Dc.Id(new Ze(this.Ne,a))};Sf[F].dc=function(a){this.Dc.Xc(new Ze(this.Ne,a))};var Vf=function(a){this.xg=a};Vf[F].kc=function(a){a.zb().ke(this.xg.id)};Vf[F].jc=function(){};Vf[F].dc=function(){};var Tf=function(a){this.m=a};
Tf[F].kc=function(a){var b=a.s.od(this.m[B]);if(!b||!b.Qb())if(b||!this.m[u])if(!b||this.m[u]||!this.m.id)if(b&&(b.Ma()||!this.m.id))this.de(b);else{var c=b,b=a.gd(this.m.id);if(b!=j)if(b.Ma()&&c)this.de(c);else{this.m[cb]?b.hb(this.m[cb]):b.Ma()&&b.hb(a.g.Vd());var d=j;this.m[Ea]&&(d=ne(this.m[Ea]));var e=j;this.m[Eb]&&(e=$e(this.m[Eb]));if(this.m[u])d||(d=c.O()),e||(e=c.Aa);this.m.clip&&b.kf(this.m.clip);if(this.m[mb])for(var f=0;f<this.m[mb][E];++f){var i=a.l().kb(this.m[mb][f].action);b.ff(this.m[mb][f].events,
this.m[mb][f][x],this.m[mb][f].keyAscii,i)}c&&a.Rb(this.m[B]);b.Ba();a.vc(b,this.m[B]);this.m[Pa]!=g&&b.Bc(this.m[Pa]);d&&b[Qa](d);this.m[Ib]&&b.be(this.m[Ib]);e&&b.Ta(e);!c&&!a.s.cf&&b[zb]()}}};Tf[F].de=function(a){this.m[Ea]&&a[Qa](ne(this.m[Ea]));this.m[Eb]&&a.Ta($e(this.m[Eb]));this.m[Pa]!=g&&a.Bc(this.m[Pa]);var b=[];this.m[Ib]&&(b=this.m[Ib]);a.be(b)};Tf[F].jc=function(){};Tf[F].dc=function(){};var Uf=function(a){this.Zc=a};
Uf[F].kc=function(a){var b=a.s.od(this.Zc[B]);if(!b||!b.Qb())b&&b.Va(),a.Rb(this.Zc[B])};Uf[F].jc=function(a){var b=a.s.od(this.Zc[B]);b&&b.Qb()&&(b.Va(),a.Rb(this.Zc[B]))};Uf[F].dc=function(){};var Wf=function(a){this.Uf=a};Wf[F].kc=function(a){var b=this.Uf,c;for(c in b[v])a.g.Ud[c]=b[v][c],a.g.Td[b[v][c]]=c};Wf[F].jc=function(){};Wf[F].dc=function(){};var Zf=function(a,b){this.eg=a;this.L=b;this.Tc=[];this.Le=k};Zf[F].Rd=function(a){this.Tc[t](a)};Zf[F].yg=function(a){uc(this.Tc,a)};Zf[F].Ze=function(){for(var a=this.Tc[E]-1;a>=0;--a)this.Tc[a].Tf();this.L.l().Ic();this.L.u()};pa(Zf[F],function(){if(!this.Le)this.Le=h,this.Ze(),aa.setInterval(R(this.Ze,this),1E3/this.eg)});var Ze=function(a,b){this.Ce=a;this.i=b};var pg=function(a,b){this.object=a;this.method=b},qg=function(a,b){this.A=a;ha(this,{});this.Q=b};N=qg[F];N.get=function(a){var b=this.A.j(this[v],a);return b in this[v]?this[v][b]:this.Q.get(a)};oa(N,function(a,b){var c=this.A.j(this[v],a);if(c in this[v])if(c=this[v][c],c instanceof pg){var d=c[ab].o[pb];if(Q(d))return d[L](c.object,b)}else{if(Q(c))return c[L](this.da(),b)}else return this.Q[K](a,b)});
N.set=function(a,b){var c=this.A.j(this[v],a);return c in this[v]?(this[v][c]=b,h):this.Q.set(a,b)};N.Ha=function(a,b){this[v][this.A.Wa(this[v],a)]=b};N.gc=function(a){a=this.A.Wa(this[v],a);a in this[v]||(this[v][a]=g)};N.sb=function(a){this.A.j(this[v],a)in this[v]||this.Q.sb(a)};la(N,function(){return"function->"+this.Q[D]()});N.W=function(a){return this.Q.W(a)};N.da=function(){return this.Q.da()};var rg=function(a,b,c){this.A=a;ha(this,c);this.Q=b};N=rg[F];
N.get=function(a){var b=this.A.j(this[v],a);return b in this[v]?this[v][b]:this.Q.get(a)};oa(N,function(a,b){var c=this.A.j(this[v],a);if(c in this[v]){if(c=this[v][c],Q(c))return c[L](this[v],b)}else return this.Q[K](a,b)});N.set=function(a,b){var c=this.A.j(this[v],a);return c in this[v]?(this[v][c]=b,h):this.Q.set(a,b)};N.Ha=function(a,b){var c=this.A.j(this[v],a);c in this[v]?this[v][c]=b:this.Q.Ha(a,b)};N.gc=function(a){this.A.j(this[v],a)in this[v]||this.Q.gc(a)};
N.sb=function(a){var b=this.A.j(this[v],a);b in this[v]?sg(this[v],b):this.Q.sb(a)};la(N,function(){return this[v]+"->"+this.Q[D]()});N.W=function(a){return this.Q.W(a)};N.da=function(){return this.Q.da()};var tg=function(a,b,c){this.A=a;ha(this,c);this.Cd=b;this.Ae=c};N=tg[F];N.get=function(a){var b=this.A.j(this[v],a);return b in this[v]?this[v][b]:a[Ub]()=="this"?this.Ae:this.Cd.get(a)};
oa(N,function(a,b){var c=this.A.j(this[v],a),d=this[v][c];if(c in this[v]){if(Q(d))return d[L](this[v],b)}else return this.Cd[K](a,b)});N.set=function(a,b){this[v][this.A.Wa(this[v],a)]=b;return h};N.Ha=function(a,b){this[v][this.A.Wa(this[v],a)]=b};N.gc=function(a){a=this.A.Wa(this[v],a);a in this[v]||(this[v][a]=g)};N.sb=function(a){var b=this.A.j(this[v],a);b in this[v]?sg(this[v],b):this.Cd.sb(a)};la(N,function(){return this[v]+""});N.W=function(a){return ha(this,a?a:this.Ae)};N.da=function(){return this[v]};
var ug=function(a,b){this.A=a;ha(this,new Z(b));this[v]._global=this[v];ae(this[v],"_global",3)};N=ug[F];N.get=function(a){return this[v][this.A.j(this[v],a)]};oa(N,function(a,b){var c=this[v][this.A.j(this[v],a)];if(Q(c))return c[L](this[v],b)});N.set=function(){return k};N.Ha=function(){};N.gc=function(){};N.sb=function(a){a=this.A.j(this[v],a);sg(this[v],a)};la(N,function(){return"_global"});N.W=function(){};N.da=function(){return j};var Ce=function(){};T(Ce,be);Ce[F].valueOf=function(){for(var a="",b=this.__swiffy_d;b&&b[Ta]();)a="."+b[Ta]()+a,b=b[ua]();b&&b instanceof Jf&&b.g.ca==b&&(a="_level0"+a);return a};
var Be={_x:{get:function(){return this.__swiffy_d.O().e/20},set:function(a){var b=this.__swiffy_d,a=ig(b,a,"_x");if(O(a)){var c=b.O();b[Qa](c.translate(a*20-c.e,0));b.ja()}}},_y:{get:function(){return this.__swiffy_d.O().f/20},set:function(a){var b=this.__swiffy_d,a=ig(b,a,"_y");if(O(a)){var c=b.O();b[Qa](c.translate(0,a*20-c.f));b.ja()}}},_xscale:{get:function(){var a=this.__swiffy_d.O();return 100*n[Xa](a.a*a.a+a.b*a.b)},set:function(a){var b=this.__swiffy_d,a=ig(b,a,"_xscale");if(O(a)){var c=b.O();
b[Qa](c.fc(a/(100*n[Xa](c.a*c.a+c.b*c.b)),1));b.ja()}}},_yscale:{get:function(){var a=this.__swiffy_d.O();return 100*n[Xa](a.c*a.c+a.d*a.d)},set:function(a){var b=this.__swiffy_d,a=ig(b,a,"_yscale");if(O(a)){var c=b.O();b[Qa](c.fc(1,a/(100*n[Xa](c.c*c.c+c.d*c.d))));b.ja()}}},_alpha:{get:function(){return this.__swiffy_d.Aa.xa*100},set:function(a){var b=this.__swiffy_d,a=ig(b,a,"_alpha");if(O(a)){var c=b.Aa;b.Ta(new Yd(c.va,c.Ka,c.ua,c.Ja,c.ta,c.Ia,a/100,c.La));b.ja()}}},_visible:{get:function(){return this.__swiffy_d.Fa},
set:function(a){var b=this.__swiffy_d,a=ig(b,a,"_visible");O(a)&&(b.sg(ea(a)),b.ja())}},_rotation:{get:function(){var a=this.__swiffy_d.O();return-180*n.atan2(a.c,a.a)/n.PI},set:function(a){var b=this.__swiffy_d,a=ig(b,a,"_rotation");if(O(a)){var c=b.O();b[Qa](c.gg(a*n.PI/-180-n.atan2(c.c,c.a)));b.ja()}}},_name:{get:function(){return this.__swiffy_d[Ta]()},set:function(a){this.__swiffy_d.hb(a);this.__swiffy_d.ja()}},_quality:{get:function(){return 0},set:function(){}},_highquality:{get:function(){return 0},
set:function(){}},_soundbuftime:{get:function(){return 0},set:function(){}},_parent:{get:function(){var a=this.__swiffy_d.pb;return a?a.B():a},set:function(){}},_xmouse:{get:function(){var a=this.__swiffy_d;return hg(a.Ga(),a.g.yc).x},set:function(){}},_ymouse:{get:function(){var a=this.__swiffy_d;return hg(a.Ga(),a.g.yc).y},set:function(){}},_url:{get:function(){return m.location.href},set:function(){}},_width:{get:function(){var a=this.__swiffy_d,b=a.ob();b.fa(a.O());return(b.J-b.C)/20},set:function(a){var b=
this.__swiffy_d,a=b.g.l().Xa(a);if(a>=0){a/=this._width;var c=b.O();b[Qa](c.fc(a,1));b.ja()}}},_height:{get:function(){var a=this.__swiffy_d,b=a.ob();b.fa(a.O());return(b.K-b.D)/20},set:function(a){var b=this.__swiffy_d,a=b.g.l().Xa(a);if(a>=0){a/=this._height;var c=b.O();b[Qa](c.fc(a,1));b[Qa](c.fc(1,a));b.ja()}}}};ae(Ce[F],j,3);var Ef=function(){};T(Ef,Ce);ae(Ef[F],j,3);var Y=function(){};T(Y,Ef);Y[F].gotoAndStop=function(a){var b=this.__swiffy_d;b.oc(b.$b(a),k)};Y[F].gotoAndPlay=function(a){var b=this.__swiffy_d;b.oc(b.$b(a),h)};Y[F].play=function(){this.__swiffy_d[Za]()};Y[F].stop=function(){this.__swiffy_d[gb]()};Y[F].nextFrame=function(){this.__swiffy_d.Te()};Y[F].prevFrame=function(){this.__swiffy_d.Ue()};Y[F].onEnterFrame=function(){};Y[F].onLoad=function(){};
Y[F].globalToLocal=function(a){var b=this.__swiffy_d,c=b.g.l(),d=c.pe(a);if(d!=j){var e=c.j(a,"x"),c=c.j(a,"y"),b=b.Ga(),d=hg(b,d);a[e]=d.x;a[c]=d.y}};Y[F].localToGlobal=function(a){var b=this.__swiffy_d,c=b.g.l(),d=c.pe(a);if(d!=j){var e=c.j(a,"x"),c=c.j(a,"y"),b=b.Ga(),d=new X(d.x*20,d.y*20);d.fa(b);d.x/=20;d.y/=20;a[e]=d.x;a[c]=d.y}};Y[F].createEmptyMovieClip=function(a,b){var c=this.__swiffy_d,d=new Jf({frameCount:0,tags:[]},c.g,c.H);d.Ub=h;d.hb(a);d.Ba();d[zb]();c.Rb(b);c.vc(d,b);return c.B()};
Y[F].attachMovie=function(a,b,c,d){var e=this.__swiffy_d,a=e.g.Ud[a];if(O(a)&&(a=e.gd(a),a.Ub=h,a.hb(b),a.Ba(),a[zb](),e.Rb(c),e.vc(a,c),O(d))){var b=a.B(),f;for(f in d)b[f]=d[f]}};Y[F].duplicateMovieClip=function(a,b,c){var d=this.__swiffy_d,e=d[ua]();if(e&&(a=d.duplicate(e,a,b),O(c))){var a=a.B(),f;for(f in c)a[f]=c[f]}};Y[F].removeMovieClip=function(){var a=this.__swiffy_d,b=a[ua]();a.Ub&&b&&(a.M(),b[ub](a))};
Y[F].swapDepths=function(a){var b=this.__swiffy_d,c=b[ua]();if(c){if(a instanceof Ce){a=a.__swiffy_d;if(a[ua]()!=c)return;a=a[B]}else a=q(a);c.Nd(b[B],a)}};l[Ma](Y[F],function(){var a={},b;for(b in Je){var c=Je[b];a[c]={get:Le,set:ec(Ke,c)}}return a}());Y[F].getBytesLoaded=function(){return this.getBytesTotal()};Y[F].getBytesTotal=function(){return 1E3};
Y[F].getBounds=function(a){var b=this.__swiffy_d,c=b.ob();if(O(a)){var d=j;a instanceof Y?d=a.__swiffy_d:P(a)&&(d=b.g.l().Sb(b,a));if(d!=j)a=d.Ga().xd(),c.fa(a.multiply(b.Ga()));else return}b={};b.C=c.C/20;b.J=c.J/20;b.D=c.D/20;b.K=c.K/20;return b};Y[F].getURL=function(a,b,c){var d=0;P(c)&&(c=c[Ub](),c=="get"?d=1:c=="post"&&(d=2));jg(this,a,b,d)};
Y[F].hitTest=function(a,b,c){if(O(a)){var d=this.__swiffy_d,e=d.ob();e.fa(d.Ga());if(!O(b)&&!O(c)){if(b=j,a instanceof Y?b=a.__swiffy_d:P(a)&&(b=d.g.l().Sb(d,a)),b!=j)return a=b.ob(),a.fa(b.Ga()),e.Nf(a)}else if(O(b))return e.contains(a*20,b*20)}return k};
var Xf={_currentframe:{get:function(){return n.max(1,this.__swiffy_d.P+1)},set:function(){}},_totalframes:{get:function(){return this.__swiffy_d.Ab},set:function(){}},_framesloaded:{get:function(){return this.__swiffy_d.qa},set:function(){}},_root:{get:function(){return this.__swiffy_d.g.ca.B()},set:function(){}},_target:{get:function(){var a=this._root;if(this==a)return"/";else{for(var b="",c=this;c&&c!=a;)b="/"+c._name+b,c=c._parent;return b}},set:function(){}},_level0:{get:function(){return this.__swiffy_d.g.ca.B()},
set:function(){}}};ae(Y[F],j,3);var ag=function(a){this.L=a};ag[F].addListener=function(){};ag[F].removeListener=function(){};l[Wa](ag[F],"height",{get:function(){return this.L.Zd/20},set:function(){}});l[Wa](ag[F],"width",{get:function(){return this.L.$d/20},set:function(){}});ae(ag[F],j,3);var Z=function(a){l[Wa](this,"__swiffy_s",{value:a});this.Color=Hf(a);ae(this,"Color",3)};Z[F].ASSetPropFlags=ae;Z[F].clearInterval=function(a){aa.clearInterval(a)};Z[F].clearTimeout=function(a){aa.clearTimeout(a)};Z[F].escape=function(a){return escape(a)[u](/[-@*+.\/_]/g,function(a){return"%"+a[Db](0)[D](16).toUpperCase()})};Z[F].parseFloat=function(a){return parseFloat(a)};Z[F].parseInt=function(a,b){return fa(a,b)};Z[F].isFinite=function(a){return isFinite(a)};Z[F].isNaN=function(a){return isNaN(a)};
Z[F].unescape=function(a){return unescape(a)};Z[F].setInterval=function(a){if(Q(a)&&arguments[E]>=2)return aa.setInterval[L](j,arguments);else if(Zb(a)&&arguments[E]>=3&&Q(a[arguments[1]])){var b=R(a[arguments[1]],a),c=arguments[2],d=ba[F][Da][K](arguments,3);return aa.setInterval[L](j,[b,c][Ha](d))}};Z[F].setTimeout=function(a,b){if(Q(a)&&arguments[E]>=2)return aa.setTimeout[L](j,arguments)};Z[F].updateAfterEvent=function(){var a=this.__swiffy_s;setTimeout(function(){a.u()},0)};Z[F].Math=n;
Z[F].MovieClip=Y;Z[F].String=r;Z[F].Number=q;Z[F].Date=de;Z[F].Array=ee;Z[F].Object=be;Z[F].Key=fe;l[Wa](Z[F],"Mouse",{get:function(){return this.__swiffy_s.Xb},set:function(){}});l[Wa](Z[F],"Stage",{get:function(){return this.__swiffy_s.mf},set:function(){}});ae(Z[F],j,3);var $f=function(a){this.I=[];this.Y=this.R=j;this.me=[];this.ia=[];this.ca=a;this.Ef=this.le();this.Oc=[];this.Kc=k;this.S=0;this.V=4;this.Yd=new ug(this,a.g)};N=$f[F];N.Id=function(a){this.Oc[t](R(function(){this.Xc(a)},this))};N.zd=function(a){this.Oc[t](a)};N.Ic=function(){if(!this.Kc){for(this.Kc=h;this.Oc[E]>0;)this.Oc[wa]()();this.Kc=k}};N.le=function(){return(new Date).getTime()};
N.reset=function(a){this.R=this.Y=a;this.I=[];this.S=0;this.V=4;this.I.length+=this.V;this.n=new tg(this,this.Yd,a.B())};N.Xc=function(a){if(!a.i.je){this.reset(a.i);for(var b=0;b<a.Ce[E];)b=a.Ce[b][K](this,b+1)}};N.ye=function(a,b){return this.bf(a)[K](this,b)};var vg=function(a){a=a[u](/\.\.|\/:?|:/g,function(a){return a==".."?"_parent":"."});a[0]=="."&&(a="_root"+a);a[a[E]-1]=="."&&(a=a.substring(0,a[E]-1));return a};
$f[F].Hc=function(a,b){if(!O(b))b=this.R;var c=a[H](":");return c[E]>1?{path:this.Sb(b,c[0]),Vb:c[1]}:{path:b,Vb:a}};$f[F].zg=function(a){for(var b=0;b<this.me[E];b++)this.me[b](a);aa.console&&aa.console.log("[trace] "+a)};var wg={"boolean":{},number:{},string:{},undefined:{}},xg=function(a){for(var b=l[va](a[Gb]),a=wg[typeof a],c=0;c<b[E];++c){var d=b[c],e=d[Ub]();d!=e&&(a[e]=d)}};xg(k);xg(0);xg("");
var yg=function(a){if(!a)return{constructor:"constructor"};var b=a.__swiffy_nm;if(!b||b.__swiffy_nm!=a){for(var b=l[jb](yg(a[Gb])),c=l[va](a),d=0;d<c[E];++d){var e=c[d],f=e[Ub]();e!=f&&(b[f]=e)}l[Wa](b,"__swiffy_nm",{value:a,writable:h});l[Wa](a,"__swiffy_nm",{value:b,writable:h})}return b};N=$f[F];
N.j=function(a,b){if(this.Y.Sa>=7){if(a instanceof Ce){if(b in a)return b;var c=b[Ub]();if(c in a&&zg[w](c)>-1)return c}return b}else{var d=wg[typeof a];if(!d){if(b in a)return b;d=yg(a)}c=b[Ub]();return(d=d[c])?d:c}};N.Wa=function(a,b){if(this.Y.Sa>=7){if(a instanceof Ce){if(b in a)return b;var c=b[Ub]();if(c in a&&zg[w](c)>-1)return c}return b}else{var d=wg[typeof a];if(d)return c=b[Ub](),(d=d[c])?d:c;else{if(b in a)return b;var e=yg(a),c=b[Ub]();return(d=e[c])?d:b==c||c in a?c:e[c]=b}}};
N.pe=function(a){if(Zb(a)){var b=a[this.j(a,"x")],a=a[this.j(a,"y")];if(typeof b=="number"&&typeof a=="number")return new X(b,a)}return j};N.W=function(a){(this.R=a)?this.n.W(a.B()):this.n.W(j)};N.da=function(){return this.R};N.push=function(a){this.I[t](a)};N.pop=function(){if(this.I[E]>this.S+this.V)return this.I.pop()};N.ed=function(a){var b=this.Y.Sa;typeof a=="boolean"&&b<5&&(a=a?"1":"0");return!O(a)&&b<7?"":a+""};
N.Xa=function(a){var b=this.Y.Sa;return!O(a)||a===j?b<7?0:q.NaN:P(a)?(a=q(a),b<5&&isNaN(a)?0:a):q(a)};N.k=function(){return this.Xa(this.pop())};N.t=function(){return this.ed(this.pop())};N.uc=function(){var a=this.pop();typeof a=="string"&&(a=q(a));return ea(a)};N.Vc=function(){var a=this.pop();if(a instanceof Ce)return a;if(a=this.Sb(this.R,r(a)))return a.B()};N.Sb=function(a,b){if(!a||!b)return a;for(var b=vg(b),c=a.B(),d=b[H]("."),e=0;e<d[E]&&c;e++)c=c[this.j(c,d[e])];return c?c.__swiffy_d:j};
N.Yf=function(a){var b=this.n.da();if(a)for(var a=vg(a),a=a[H]("."),c=0;c<a[E]&&b;c++)b=b[this.j(b,a[c])];return b};N.Bf=function(a,b,c,d){this.Kc||this.reset(c);a=this.Hc(a,c);if(a[z]){var c=a[z].B(),e=this.Wa(c,a.Vb);O(a[z].Pb[e])||(a[z].Pb[e]=[]);a[z].Pb[e][t](b);if(e in c&&(b.ud(r(c[e])),d=c[e],l[vb](c,e).get))return;l[Wa](c,e,Ag(d,a[z].Pb[e]))}};var Ag=function(a,b){var c=a;return{get:function(){return c},set:function(a){c=a;for(var e=0;e<b[E];e++)b[e].ud(a)},configurable:h}};
$f[F].Kf=function(a,b,c){a=this.Hc(a,c);a[z]&&(c=this.j(a[z].B(),a.Vb),uc(a[z].Pb[c],b))};var sg=function(a,b){delete a[b];if(a instanceof Y){var c=a.__swiffy_d.s.ig(b);c&&xe(a,c,b)}};$f[F].kb=function(a){for(var b=[],c=0;c<a[E];++c)b[c]=this.bf(a[c]);return b};$f[F].bf=function(a){var b=$[a[C]];return!b?R(Bg,this,a[C]):b.$?b(a,this):b};
var zg="_x,_y,_xscale,_yscale,_currentframe,_totalframes,_alpha,_visible,_width,_height,_rotation,_target,_framesloaded,_name,_droptarget,_url,_highquality,_focusrect,_soundbuftime,_quality,_xmouse,_ymouse".split(","),$={4:function(a){var b=this.R;b!=j&&b.Te();return a},5:function(a){var b=this.R;b!=j&&b.Ue();return a},6:function(a){var b=this.R;b!=j&&b[Za]();return a},7:function(a){var b=this.R;b!=j&&b[gb]();return a},9:function(a){var b=this.R;b!=j&&b.zb().mg();return a},10:function(a){var b=this.k();
this[t](this.k()+b);return a},11:function(a){var b=this.k();this[t](this.k()-b);return a},12:function(a){var b=this.k();this[t](this.k()*b);return a},13:function(a){var b=this.k();this[t](this.k()/b);return a},14:function(a){var b=this.k(),b=this.k()==b;this.Y.Sa<5&&(b=b?1:0);this[t](b);return a},15:function(a){var b=this.k();this[t](this.k()<b);return a},16:function(a){var b=this.uc();this[t](this.uc()&&b);return a},17:function(a){var b=this.uc();this[t](this.uc()||b);return a},18:function(a){this[t](!this.uc());
return a},19:function(a){var b=this.t();this[t](this.t()==b);return a},20:function(a){this[t](this.t()[E]);return a},21:function(a){var b=q(this.pop()),c=n.max(0,q(this.pop())-1);this[t](this.t().substr(c,b));return a},23:function(a){this.pop();return a},24:function(a){var b=this.k(),b=b<0?n.ceil(b):n[Ga](b);this[t](b);return a},28:function(a){var b=this.t(),b=vg(b),b=b[H]("."),c=this.n.get(b[0]);if(b[E]>1){var d;for(d=1;O(c)&&d<b[E]-1;++d)c=c[this.j(c,b[d])];O(c)&&(c=c[this.j(c,b[d])])}this[t](c);
return a},29:function(a){var b=this.pop(),c=this.t(),c=vg(c),d=c[H](".");if(d[E]==1)this.n.set(c,b);else{var c=this.n.get(d[0]),e;for(e=1;O(c)&&e<d[E]-1;++e)c=c[this.j(c,d[e])];O(c)&&(c[this.Wa(c,d[e])]=b)}return a},33:function(a){var b=this.t();this[t](this.t()+b);return a},34:function(a){var b=zg[this.k()],c=this.Vc();c?this[t](c[b]):this[t](g);return a},35:function(a){var b=this.pop(),c=zg[this.k()],d=this.Vc();d&&c&&(d[c]=b);return a},36:function(a){var b=this.k(),c=this.t(),d=this.Vc();d&&d.__swiffy_d.duplicate(this.R,
c,b);return a},37:function(a){var b=this.Vc();b instanceof Y&&b.removeMovieClip();return a},38:function(a){var b=this.pop();this.zg(O(b)?this.ed(b):"undefined");return a}},Bg=function(a,b){return b};$[51]=function(a){var b=this.k();this[t](r.fromCharCode(b));return a};$[50]=function(a){this[t](this.t()[Db](0));return a};$[52]=function(a){this[t](this.le()-this.Ef);return a};$[48]=function(a){var b=this.k(),c;do c=n[Ga](n.random()*b);while(c==b&&b>0);this[t](c);return a};
$[60]=function(a){var b=this.pop();this.n.Ha(this.pop(),b);return a};$[65]=function(a){this.n.gc(this.pop());return a};$[59]=function(a){var b=this.t(),b=vg(b),c=b[H](".");if(c[E]==1)this.n.sb(b);else{var b=this.n.get(c[0]),d;for(d=1;O(b)&&d<c[E]-1;++d)b=b[this.j(b,c[d])];O(b)&&sg(b,this.j(b,c[d]))}return a};$[62]=function(){qa(this,this.pop());return q.MAX_VALUE};$[63]=function(a){var b=this.k();this[t](this.k()%b);return a};
$[71]=function(a){var b=this.pop(),c=this.pop();P(b)||P(c)?this[t](this.ed(c)+this.ed(b)):this[t](this.Xa(c)+this.Xa(b));return a};$[72]=function(a){var b=this.pop(),c=this.pop();if(!P(b)||!P(c))b=this.Xa(b),c=this.Xa(c);b!==b||c!==c?this[t](g):this[t](c<b);return a};$[103]=function(a){var b=this.pop();this[t](this.pop()>b);return a};$[73]=function(a){var b=this.pop();this[t](this.pop()==b);return a};$[102]=function(a){var b=this.pop();this[t](this.pop()===b);return a};
$[41]=function(a){var b=this.t();this[t](this.t()<b);return a};$[104]=function(a){var b=this.t();this[t](this.t()>b);return a};$[105]=function(a){var b=this.pop(),c=this.pop();T(c,b);return a};$[74]=function(a){this[t](this.k());return a};$[75]=function(a){this[t](this.t());return a};$[76]=function(a){var b=this.pop();this[t](b);this[t](b);return a};$[77]=function(a){var b=this.pop(),c=this.pop();this[t](b);this[t](c);return a};
$[78]=function(a){var b=this.t(),c=this.pop(),d=g;c&&(d=c[this.j(c,b)]);this[t](d);return a};$[79]=function(a){var b=this.pop(),c=this.t(),d=this.pop();d&&(d[this.Wa(d,c)]=b);return a};$[80]=function(a){var b=this.k();this[t](++b);return a};$[81]=function(a){var b=this.k();this[t](--b);return a};$[96]=function(a){var b=this.k(),c=this.k();this[t](b&c);return a};$[97]=function(a){var b=this.k(),c=this.k();this[t](b|c);return a};$[98]=function(a){var b=this.k();this[t](this.k()^b);return a};
$[99]=function(a){var b=this.k();this[t](this.k()<<b);return a};$[100]=function(a){var b=this.k();this[t](this.k()>>b);return a};$[101]=function(a){var b=this.k();this[t](this.k()>>>b);return a};$[58]=function(a){var b=this.t(),c=this.pop();c&&sg(c,this.j(c,b));return a};$[129]=function(a,b){return R(Cg,b,a.frame)};$[129].$=h;var Cg=function(a,b){var c=this.R;c!=j&&c.oc(a,k);return b};$[140]=function(a,b){return R(Dg,b,a.label)};$[140].$=h;
var Dg=function(a,b){var c=this.R;if(c!=j){var d=c.$b(a);d!=g&&c.oc(d,k)}return b};$[136]=function(a,b){return R(Eg,b,a.constants)};$[136].$=h;var Eg=function(a,b){this.ia=a;return b};$[32]=function(a){var b=this.pop();b=b instanceof Ce?b.__swiffy_d:(b=r(b))?this.Sb(this.Y,b):this.n.W(j).__swiffy_d;this.W(b);return a};$[69]=function(a){var b=this.pop(),c=g;b instanceof Ce&&(c=b.valueOf());this[t](c);return a};$[305]=function(a,b){return R(Fg,b,a.value)};$[305].$=h;
var Fg=function(a,b){this[t](a);return b};$[306]=function(a){this[t](g);return a};$[307]=function(a){this[t](q[ya]);return a};$[308]=function(a){this[t](q.NEGATIVE_INFINITY);return a};$[309]=function(a){this[t](q.NaN);return a};$[304]=function(a,b){return R(Gg,b,a.index)};$[304].$=h;var Gg=function(a,b){this[t](this.ia[a]);return b};$[303]=function(a,b){return R(Hg,b,a.index)};$[303].$=h;var Hg=function(a,b){a>=0&&a<this.V?this[t](this.I[this.S+a]):this[t](g);return b};
$[135]=function(a,b){return R(Ig,b,a.index)};$[135].$=h;var Ig=function(a,b){a>=0&&a<this.V&&(this.I[this.S+a]=this.I[this.I[E]-1]);return b};$[154]=function(a,b){return R(Jg,b,a[ab])};$[154].$=h;var Jg=function(a,b){var c=this.t(),d=this.t();jg(this.R.B(),d,c,a);return b};$[148]=function(a,b){return R(Kg,b,b.kb(a[tb]))};$[148].$=h;var Kg=function(a,b){var c=this.pop();if(!(c instanceof be))return b;var d=this.n;this.n=new rg(this,d,c);for(c=0;c<a[E];)c=a[c][K](this,c+1);this.n=d;return b};
$[155]=function(a,b){return R(Lg,b,a.args,b.kb(a[tb]))};$[155].$=h;
var Lg=function(a,b,c){var d=this,e=this.ia,f=this.n,i=function(){var c=d.n,i=d.S,A=d.V,ca=d.ia,V=d.R,eb=d.Y,I;d.Y.Sa>5?(I=f,d.n=new qg(d,I),d.W(f.da().__swiffy_d)):(I=new tg(d,d.Yd,this),d.n=new qg(d,I),this instanceof Ce&&d.W(this.__swiffy_d));d.ia=e;d.S=d.I[E];d.V=4;d.I.length+=d.V;for(I=0;I<a[E];++I)d.n.Ha(a[I],arguments[I]);d.n.Ha("this",this);qa(d,g);for(I=0;I<b[E];)I=b[I][K](d,I+1);ma(d.I,d.S);d.n=c;d.S=i;d.V=A;d.ia=ca;d.Y=eb;d.R=V;return d[Cb]};T(i,be);this[t](i);return c};
$[142]=function(a,b){return R(Mg,b,a.args,b.kb(a[tb]),a.preloads,a.suppress,a.registerCount)};$[142].$=h;
var Mg=function(a,b,c,d,e,f){var i=this,o=this.ia,p=this.n,A=function(){var f=i.n,A=i.S,eb=i.V,I=i.ia,Tb=i.da(),Sa=i.Y;i.n=new qg(i,p);i.ia=o;i.W(p.da().__swiffy_d);i.S=i.I[E];i.V=e;i.I.length+=i.V;d&4||i.n.Ha("this",this);d&1||i.n.Ha("super",new pg(this,arguments.callee));for(var S=0;S<c[E]&&S+1<e;++S)i.I[i.S+S+1]=i.n.get(c[S]);for(S=0;S<a[E];++S)P(a[S])?i.n.Ha(a[S],arguments[S]):i.I[i.S+a[S]]=arguments[S];qa(i,g);for(S=0;S<b[E];)S=b[S][K](i,S+1);ma(i.I,i.S);i.n=f;i.S=A;i.V=eb;i.ia=I;i.Y=Sa;i.W(Tb);
return i[Cb]};T(A,be);this[t](A);return f};$[61]=function(a){for(var b=this.t(),c=this.k(),d=[],e=0;e<c;++e)d[e]=this.pop();this[t](this.n[K](b,d));return a};
$[82]=function(a){for(var b=this.pop(),c=this.pop(),d=this.k(),e=[],f=0;f<d;f++)e[f]=this.pop();if(c!=j)if(b){var d=g,i;if(c instanceof pg){i=c.object;for(var o=k,p=i[pb];p;p=p.o&&p.o[pb]){if(o){d=p[F][r(b)];break}for(var A=l[va](p[F]),f=0;f<A[E]&&!o;f++)p[F][A[f]]===c[ab]&&(o=h)}}else d=c[this.j(c,r(b))],i=c;d?this[t](d[L](i,e)):this[t](g)}else if(c instanceof pg)b=c[ab].o[pb],Q(b)?this[t](b[L](c.object,e)):this[t](g);else this[t](c[L](this.n.da(),e));else this[t](g);return a};
$[64]=function(a){for(var b=this.n.get(this.t()),c=this.k(),d=[],e=0;e<c;++e)d[e]=this.pop();Q(b)||(b=be);c=l[jb](b[F]);b[L](c,d);this[t](c);return a};$[83]=function(a){for(var b=this.pop(),c=this.pop(),d=this.k(),e=[],f=0;f<d;f++)e[f]=this.pop();d=g;c!=j&&(d=b?c[this.j(c,r(b))]:c);Q(d)||(d=be);b=l[jb](d[F]);d[L](b,e);this[t](b);return a};$[84]=function(a){var b=this.pop(),c=this.pop(),d=k;Q(b)&&(d=c instanceof b);this[t](d);return a};
$[67]=function(a){for(var b=new be,c=this.k(),d=0;d<c;d++){var e=this.pop(),f=this.t();b[f]=e}this[t](b);return a};$[66]=function(a){for(var b=[],c=this.k(),d=0;d<c;d++){var e=this.pop();b[d]=e}this[t](b);return a};$[68]=function(a){var b=this.pop();this[t](b instanceof Y?"movieclip":b==j||b==g?r(b):typeof b);return a};$[85]=function(a){var b=this.pop();this[t](g);for(var c in b)this[t](c);return a};$[153]=function(a,b){return R(Ng,b,a[wb])};$[153].$=h;var Ng=function(a){return a};
$[157]=function(a,b){return R(Og,b,a[wb])};$[157].$=h;var Og=function(a,b){return ea(this.pop())?a:b};$[158]=function(a){var b=this.Hc(this.t());if(b[z]){var c=b[z].$b(b.Vb);if(c!=g&&(c=b[z].Gf(c))){for(var d=this.n,e=this.S,f=this.V,i=this.ia,o=this.da(),p=this.Y,A=this.I,ca=0;ca<c[E];ca++)c[ca].dc(b[z]);this.I=A;this.n=d;this.S=e;this.V=f;this.ia=i;this.Y=p;this.W(o)}}return a};$[159]=function(a,b){return R(Pg,b,a.frameBias,a[Za])};$[159].$=h;
var Pg=function(a,b,c){var d=this.Hc(this.t());if(d[z]){var e=d[z].$b(d.Vb);e!=g&&d[z].oc(e+a,b)}return c};
